### ISSUE TITLE
Mounting of FS images?

### ISSUE THREAD

**Issue by oschulz** [proot-me/PRoot#101]
It would be awesome if proot would support (read-only) mounting of file system images (e.g. SquashFS, ISO, ...). This would be especially useful for the root file-system, as it usually contains many small files - which impacts performance when using networked file systems (e.g. to run on many systems in parallel).
Would this be possible at all (e.g. using libguestfs)? Accessing the fs image contents via proot/ptrace would keep metadata operations inside the "prooted" process, and could result in much higher performance when using networked storage.

**Comment by insulsa** [comment]
Why not first mounting such images by FUSE? I don't get why leveraging the same load of metadata operations from one place to another helps with performance. If you like to cache such metadata in memory or discard them, It's achievable or already implemented with FUSE drivers or other wrapper programmes.

**Comment by oschulz** [comment]
On compute clusters, users often don't get FUSE privileges. In any case, this use case is now pretty much covered by Singularity.
