### ISSUE TITLE
Small(er) example of using PRoot as a generic syscall interception framework

### ISSUE THREAD

**Issue by copumpkin** [proot-me/proot#103]
The PRoot documentation states:

> Also, developers can use PRoot as a generic Linux process instrumentation engine thanks to its extension mechanism, see CARE_ for an example.

But CARE is a pretty big meaty example with a lot of its own logic in addition to the syscall stuff it uses PRoot to manage. I was wondering if you could bundle a minimal example that just shows how to build a minimal program that intercepts one or two syscalls in the endorsed PRoot manner and does something trivial (like print args before passing control to original syscall) before returning.

Is there such an example already floating around?

**Comment by ivoire** [comment]
A long time ago, I payed with PRoot to make a strace like https://github.com/ivoire/PRoot/tree/pstrace.
This is not finished and unfortunately I don't have time to work on it anymore.

**Comment by vincenthage** [comment]
Hi,
If you're still looking for an example, I've developed a small extension [here](https://github.com/vincenthage/PRoot/tree/master/src/extension/portmap) that intercepts the bind and connect system calls and changes their parameters.

**Comment by oxr463** [comment]
Closing since the portmap extension written by @vincenthage has already been merged.
