### ISSUE TITLE
question: how to share multiple paths

### ISSUE THREAD

**Issue by QiangF** [proot-me/PRoot#109]
For example, the root home and tmp are on three seperate partitions,

    ./proot-x86_64 -r /media/usb0 -b /media/usb1:/home /media/usb2:/tmp

How to make the above command work?

**Comment by QiangF** [comment]
OK, it works when I put -b in front of each path. It's not very clear in the document. Also the difference between -b and -m.

**Comment by jopasserat** [comment]
Hi @QiangF, would you be happy to fill in a PR updating the doc in a way you think is clearer?
Would be great!

**Comment by QiangF** [comment]
@jopasserat I am willing to, but I don't know how to do it properly.  I think the following need some explanation.
1 what is the difference between the following format:

     -b /etc/host.conf 
     -b /media/usb1:/home

2 which configration takes effect if multiple -b *path* to the same destination, like

    -b /test1:/test  -b /test2:test

what happens if /test is not empty on the change root.
3 what is the difference between -b and -m?

**Comment by jopasserat** [comment]
1. First one binds to the same location in rootfs, second one binds to the specified location (check that out https://github.com/proot-me/PRoot/blob/master/doc/proot/manual.txt)
2. The last one always overwrites the others, if `/test` is not empty, it's shadowed, just as it would be when mounting a filesystem on your machine using `mount`
3. It's an alias according to [the manual](https://github.com/proot-me/PRoot/blob/master/doc/proot/manual.txt)

If you want to suggest changes to the [user guide](http://proot-me.github.io/), please open a PR on [this repo](https://github.com/proot-me/proot-me.github.io).

To modify [the manual / documentation](https://github.com/proot-me/PRoot/blob/master/doc/proot/manual.txt), then PR on the main PRoot repo.

For this kind of general questions, I'd say it's better to post on [the mailing list](https://groups.google.com/forum/?fromgroups#!forum/proot_me) as long as they're not problems / features enhancements to the code base itself.

Would be great if you could contribute your suggestions to the user guide and / or manual though :)
