### ISSUE TITLE
Domain reproducible.io down ?

### ISSUE THREAD

**Issue by dja-fr** [proot-me/PRoot#113]
Hi, 
when I read the CARE's documentation I see the following link for downloading the binary : 
- http://static.reproducible.io/care-x86
- http://static.reproducible.io/care-x86_64

Unfortunatly links are broken and the domain name seem to be reserved by "NameCheap" company.

Is there another url to download the binary ?

Thx

**Comment by jopasserat** [comment]
Hi @dja-fr 

You can find the latest stable binaries here:
https://github.com/proot-me/proot-static-build/tree/master/static

and the future release will land here:
https://github.com/proot-me/proot-static-build/releases

I've updated the references to the website, the new domain is https://proot-me.github.io/

Feel free to create a PR if you spot other locations where this should be updated.
