### ISSUE TITLE
GNUMakefile problem

### ISSUE THREAD

**Issue by VGib** [proot-me/PRoot#114]
Hello ,

I have identifyied 2 problems in your makefile:
1°) the makefile version should be 1
V = 0 --> V = 1
2°) the script for OBJIFY daesn't produce the right output on my computer.
As I'm not a C++ expert, I can't provide a patch for this point.

**Comment by alkino** [comment]
Can you be more explicit on "doesn't produce the right output" please?

**Comment by VGib** [comment]
Hello, here are the need informations

## Code with problems
1. env LANG=C $(OBJDUMP) -f cli/cli.o |				\
			grep 'file format' | awk '{print $$4}'
2.  env LANG=C $(OBJDUMP) -f cli/cli.o |		\
				grep architecture | cut -f 1 -d , | awk '{print $$2}'

## Output on my computer
1. nothing
2. i386:x86-64

## Expected (I hard write this in the GNUMakefile )
1. elf64-x86-64
2. i386

## output of objdump
vincent@vincent src]$ objdump -f cli/cli.o 

cli/cli.o:     format de fichier elf64-x86-64
architecture: i386:x86-64, fanions 0x00000011:
HAS_RELOC, HAS_SYMS
adresse de départ 0x0000000000000000

(I'm french, I'm sorry)

**Comment by VGib** [comment]
I will ask to add your version to the package

**Comment by alkino** [comment]
The problem seems to be that even if you set LANG=C your locale is still french.
Can you do `LANG=C cat foo_bar_no_exist`?

By the way, I'm french too and I am the maintainer of archlinux package.

**Comment by VGib** [comment]
Yes it's seems to be in french, I don't know why
cat: foo_bar_no_exist: Aucun fichier ou dossier de ce type

**Comment by alkino** [comment]
So this is a problem with your environment. Not a problem of PRoot.

**Comment by christophe-lyon** [comment]
Sorry, I beg to differ.
It seems clear that the makefile is not immune to the user locale.
And it seems that 'LANG=C' in GNUmakefile is an attempt at avoiding such problems.
Wouldn't LC_ALL=C work?
Or LANGUAGE=C ?

**Comment by VGib** [comment]
LC_ALL is working nicely.

What about using V=1 for the makefile ?

**Comment by alkino** [comment]
Thanks, here is the fix.

For V=1 it doesn't make PRoot verbose, it makes the make of PRoot verbose so there is no point to set it by default.
