### ISSUE TITLE
proot.me no longer resolves

### ISSUE THREAD

**Issue by ocharles** [proot-me/PRoot#118]

**Comment by gbraad** [comment]
You can find downloads at: https://github.com/proot-me/proot-static-build/releases

**Comment by jopasserat** [comment]
the new website is hosted at https://proot-me.github.io/
closed as duplicate of #113
please open PR if you find occurrences of the old URL in the code

**Comment by hugobuddel** [comment]
Also, those binaries seem quite old, like from 2016, are the binaries not built anymore?
https://github.com/proot-me/proot-static-build/issues/5
