### ISSUE TITLE
Binary URLs broken

### ISSUE THREAD

**Issue by matthewbauer** [proot-me/PRoot#120]
The page at https://proot-me.github.io/ refers to static binary URLs that are no longer available:

- http://portable.proot.me/proot-x86_64
- http://portable.proot.me/proot-x86
- http://portable.proot.me/proot-arm

Can these be mirrored on GitHub?

**Comment by ahane** [comment]
https://github.com/proot-me/proot-static-build

**Comment by jopasserat** [comment]
The idea is to have them generated automatically from Travis at some point.
You can use this sequence of instructions to build them from the source in the meantime: https://github.com/proot-me/PRoot/blob/f9e8b7f509bbff0f9d5c8486d8290346f0acd3fd/.travis.yml#L17-L26

**Comment by willprice** [comment]
FWIW I didn't realise the link @ahane posted had compiled binaries inside, I thought it was just scripts to build the binaries so cloned the *huge* repo.

Here are the direct download links for the binaries

* [`proot-x86](https://github.com/proot-me/proot-static-build/blob/master/static/proot-x86?raw=true)
* [`proot-x86_64`](https://github.com/proot-me/proot-static-build/blob/master/static/proot-x86_64?raw=true)

**Comment by oxr463** [comment]
The website has just been updated with these links.
