### ISSUE TITLE
Travis CI and pull requests

### ISSUE THREAD

**Issue by vincenthage** [proot-me/PRoot#122]
Hi,
Travis CI has been renabled on this repos;
it should make PR-merging easier, as it looks like most of them are frozen.
And by that I mean PRs that are probably working and only missing throughout testing on multiple environments. 

So now when introducing a new feature or a bug fix, we should also add a test along it
(or is-it too much and it would slow down PR merging even more?).

Any commit/merge on master, and update on pull requests will trigger a run,
but the existing pull requests won't be run until they are updated in some way
so we will have to manually update them (either with a commit or by closing/opening them).

If you have any comment about the current state of PRoot and how to improve it,
don't mind leaving a message here.

Cheers,
Vincent

**Comment by jopasserat** [comment]
Maybe we should specify / clarify a branching policy as well?
It seems there are some new features in `next`.
Do you think all PRs should be done against `next` and then `next` would be merged into `master` upon release?

**Comment by oxr463** [comment]
- [ ] Update `.travis.yml`
- [] Update README.md to point to appropriate URLS

**Comment by oxr463** [comment]
@vincenthage, it looks like you already applied those fixes in the [travis branch](https://github.com/proot-me/PRoot/tree/travis). Where you able to fix Coverity? It looks like it is still pointing to the old URL.

**Comment by oxr463** [comment]
https://github.com/mcandre/linters/blob/master/README.md#c

**Comment by oxr463** [comment]
> So now when introducing a new feature or a bug fix, we should also add a test along it
(or is-it too much and it would slow down PR merging even more?).

As a new contributor, I am finding a hard time figuring out what the tests actually do; the names aren't very descriptive. Perhaps we should include a comment in each test summarizing what the test does?
