### ISSUE TITLE
Permission denied on recent kernels even without seccomp

### ISSUE THREAD

**Issue by tpimh** [proot-me/PRoot#125]
I'm on Arch Linux (kernel 4.12.8) and recently proot stopped working for me even with PROOT_NO_SECCOMP=1. I think the cause of it is the kernel upgrade. Here is the output:

    proot error: execve("/hello.static"): Permission denied
    proot info: possible causes:
      * the program is a script but its interpreter (eg. /bin/sh) was not found;
      * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
      * the program is a foreign binary but qemu was not specified;
      * qemu does not work correctly (if specified);
      * the loader was not found or doesn't work.
    fatal error: see `proot-x86_64 --help`.
    proot error: can't chmod '/tmp/proot-3858-OYwwr2': No such file or directory

**Comment by vincenthage** [comment]
Hello,
Can you activate the verbose (`proot -v 2`, lvl 2 should be enough) and paste the content of it so that we can get more details.

**Comment by tpimh** [comment]
proot info: binding = /opt/build/ngtc-modern/alpine
    proot info: binding = /home/build
    proot info: binding = /tmp
    proot info: binding = /proc
    proot info: binding = /sys
    proot info: binding = /dev
    proot info: binding = /run/systemd/resolve/resolv.conf:/etc/resolv.conf
    proot info: binding = /etc/nsswitch.conf
    proot info: binding = /etc/hosts
    proot info: binding = /etc/host.conf
    proot info: binding = /opt/build/ngtc-modern/alpine:/
    proot info: pid 1994: translate("/" + "/hello.static")
    proot info: pid 1994:          -> "/opt/build/ngtc-modern/alpine/hello.static"
    proot info: pid 1994: translate("/" + "/hello.static")
    proot info: pid 1994:          -> "/opt/build/ngtc-modern/alpine/hello.static"
    proot info: glue rootfs = /tmp/proot-1994-J4d3dC
    proot info: exe = /hello.static
    proot info: argv = /hello.static
    proot info: initial cwd = /opt/build/ngtc-modern
    proot info: verbose level = 2
    proot info: pid 1994: access to "/dev/pts/0" (fd 0) won't be translated until closed
    proot info: pid 1994: access to "/dev/pts/0" (fd 1) won't be translated until closed
    proot info: pid 1994: access to "/dev/pts/0" (fd 2) won't be translated until closed
    proot info: pid 1994: access to "/proc/1994/fd" (fd 3) won't be translated until closed
    proot info: ptrace acceleration (seccomp mode 2) enabled
    proot info: pid 1995: translate("/" + "/hello.static")
    proot info: pid 1995:          -> "/opt/build/ngtc-modern/alpine/hello.static"
    proot info: loader: /tmp/prooted-1994-65nRYI
    proot error: execve("/hello.static"): Permission denied
    proot info: possible causes:
      * the program is a script but its interpreter (eg. /bin/sh) was not found;
      * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
      * the program is a foreign binary but qemu was not specified;
      * qemu does not work correctly (if specified);
      * the loader was not found or doesn't work.
    fatal error: see `proot.static --help`.
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/opt/build/ngtc-modern/alpine")
    proot info: pid 1995:          -> "/opt/build/ngtc-modern/alpine/opt/build/ngtc-modern/alpine"
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/opt/build/ngtc-modern/alpine")
    proot info: pid 1995:          -> "/opt/build/ngtc-modern/alpine/opt/build/ngtc-modern/alpine"
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/opt/build/ngtc-modern")
    proot info: pid 1995:          -> "/opt/build/ngtc-modern/alpine/opt/build/ngtc-modern"
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/opt/build/ngtc-modern")
    proot info: pid 1995:          -> "/opt/build/ngtc-modern/alpine/opt/build/ngtc-modern"
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/opt/build")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/opt")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/home/build")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/home")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/tmp")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/proc")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/sys")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/dev")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/etc/resolv.conf")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/etc/nsswitch.conf")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/etc/hosts")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/etc/host.conf")
    proot info: pid 1995: translate("/" + "/opt/build/ngtc-modern/alpine/etc")
    proot info: pid 1995: translate("/opt/build/ngtc-modern" + ".")
    proot info: pid 1995: translate("/opt/build/ngtc-modern" + ".")
    proot info: pid 1995: translate("/" + "/tmp/proot-1994-J4d3dC")
    proot info: pid 1995:          -> "/tmp/proot-1994-J4d3dC"
    proot info: pid 1995: translate("/" + "/tmp/proot-1994-J4d3dC/.")
    proot info: pid 1995:          -> "/tmp/proot-1994-J4d3dC/."
    proot info: pid 1995: translate("/" + "/proc/self/cwd")
    proot info: pid 1995:          -> "/proc/1995/cwd"
    proot info: pid 1995: translate("/tmp/proot-1994-J4d3dC" + ".")
    proot info: pid 1995:          -> "/tmp/proot-1994-J4d3dC/."
    proot info: pid 1995: translate("/tmp/proot-1994-J4d3dC" + "../.")
    proot info: pid 1995:          -> "/tmp/."
    proot info: pid 1995: translate("/" + "/tmp/proot-1994-J4d3dC")
    proot info: pid 1995:          -> "/tmp/proot-1994-J4d3dC"
    proot info: pid 1995: exited with status 1
    proot error: can't chmod '/tmp/proot-1994-J4d3dC': No such file or directory

**Comment by tpimh** [comment]
Just tested it with LTS kernel (4.9.44) and it didn't work, so I don't know what actually did break it. It was working perfectly about a week ago.

**Comment by vincenthage** [comment]
Looks like this issue:
https://github.com/proot-me/PRoot/pull/107

You binary might not have this fix.

**Comment by tpimh** [comment]
Thank you! Looks like it was my fault. My `/tmp` was mounted with `noexec` option. After `mount -o exec,remount /tmp` it works fine.

**Comment by vincenthage** [comment]
Glad your problem was fixed!
