### ISSUE TITLE
Creating a new Release

### ISSUE THREAD

**Issue by makefu** [proot-me/proot#127]
Right now all big distros (debian,ubuntu,arch,gentoo) package the official 5.1.0 release which is based on source code of 2014.
Right now we are discussing at NixOS (another distro) if we should either follow your master branch or use the patches from debian.

it would be fantastic if a new release could be published based on all the improvements you did over the last 3 years.

Related: https://github.com/NixOS/nixpkgs/pull/29985#issuecomment-333377556

**Comment by nckx** [comment]
I just want to voice my enthusiastic support here — and hopefully fire off another ping to somebody's in-box.

It's disheartening that this issue hasn't received any comments in 4 months. There's so much good work in master that deserves to be released properly. Is anything blocking that?

**Comment by jopasserat** [comment]
yes, mainly two issues:
  - [ ] there cannot be a release without issue #106 fixed (PR #130 from the @jorge-lip is the best candidate at the moment but needs further investigation after reports it introduced another problem from @walterbrebels
  - [ ] merge #126 to have a simple build and release workflow. just need to add a publish to bintray hook to finalise this one

Any help welcome!

**Comment by alkino** [comment]
And for the #106 we need to understand ptrace, seccomp and the internal state machine of proot. And it's not easy.

**Comment by nckx** [comment]
I didn't respond because I can't help out with those things (certainly not seccomp), but thanks for both your answers!

**Comment by mirage335** [comment]
Please resolve this in the near future. Application directory redirection can be an invaluable feature on modern operating systems.

**Comment by oxr463** [comment]
[Unreleased](https://github.com/proot-me/proot/compare/v5.1.0...HEAD)

See: https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

**Comment by oxr463** [comment]
Please see: https://github.com/proot-me/proot/releases/tag/v5.2.0-alpha
