### ISSUE TITLE
merge link2symlink branch

### ISSUE THREAD

**Issue by michele13** [proot-me/proot#132]
when will the link2symlink option be added into the master branch? it's a useful feature that could help users who can't create hardlinks on restricted environments

**Comment by jopasserat** [comment]
what PR is that?
did you test it yourself? would be great to have some feedback to make sure it's working

**Comment by michele13** [comment]
the link2symlink version is a brench of PRoot. Some android packages use a modified version of PRoot which has this neat feature. Android, as we know does not allow us to make hard links anymore. this PRoot binary intercepts any attempt to create a hardlink and creates a symlink instead..This is useful because certain programs use hardlinks to work. Such programs are: GCC. (it has lots of hardlinks) Python3 (tries to create a hardlink called python3.6 pointing to python3.6m), dropbear (to generate keys), etc

**Comment by alkino** [comment]
He is talking about https://github.com/proot-me/PRoot/commits/link2symlink
It needs a good rebase.

**Comment by alkino** [comment]
Hi michele.
I merge last master in link2symlink and add an option(`-l`) to enable it.
Can you test the last version of the link2symlink branch?
Thank you.

**Comment by michele13** [comment]
Unfortunately it says that the '-l' option is not recognized. I tried the command `proot -l -r /`

**Comment by alkino** [comment]
Do you really compile the `link2symlink` branch?

**Comment by oxr463** [comment]
See also: https://github.com/proot-me/PRoot/issues/95
