### ISSUE TITLE
"is not a regular file" error

### ISSUE THREAD

**Issue by gwerbin** [proot-me/PRoot#133]
What am I doing wrong?

```shell
curl -sL -o ~/.local/bin/proot-x86_64 'https://github.com/proot-me/proot-static-build/blob/master/static/proot-x86_64?raw=true'
chmod +x ~/.local/bin/proot-x86_64
mkdir ~/.local/nix
~/.local/bin/proot-x86_64 ~/.local/nix
# proot error: '¯\_(ツ)_/¯/.local/nix' is not a regular file
# fatal error: see `proot-x86_64 --help`.
```

This is on Linux kernel 3.10.0 on an x86_64 system, with a non-administrator account.

edit: it seems like the instructions from https://nixos.wiki/wiki/Nix_Installation_Guide#PRoot are out of date, as it looks like the CLI is different from what those expect. Not sure if I should close this. The closest I've gotten was `proot -S / /bin/sh` but that doesn't appear to act like a chroot at all -- e.g. `pwd` doesn't show `/` it shows whatever directory I was already in.

**Comment by jluttine** [comment]
@gwerbin Did you manage to get it working? I'm following those NixOS wiki instructions and have the same issue so I was wondering if there is some way to use PRoot..

**Comment by ignesco** [comment]
Looks like the -b option is needed:

mkdir -m 0755 ~/.nix
`./proot_5.1.1_x86_64_rc2--no-seccomp  -b ~/.nix:/nix`

Now it should be possible to run the standard nix package manager install instructions

N.B. Be sure to fully logout after installing nix so that .nix-profile is loaded.

**Comment by gwerbin** [comment]
@ignesco it worked, thank you!
