### ISSUE TITLE
Is this a P-Root issue or a gnuroot issue?

### ISSUE THREAD

**Issue by Root-voidX** [proot-me/PRoot#135]
Does P-Root have limitations which cause packages like gmsh, scilab, paraview and even simulation solvers to not run and/or cause segmentation faults? Also does P-Root support arm64?

Sorry if this is not directly related to proot, I am a beginner in this.

**Comment by lramage94** [comment]
Can you please add more information on how those packages are failing? 
Attach any relevant logs, operating system version, etc.

Yes, arm64 is supported.

https://github.com/proot-me/proot-static-build/blob/master/static/proot-arm64

**Comment by oxr463** [comment]
@Root-voidX are you still experiencing problems with this or has your issue been resolved?

**Comment by Root-voidX** [comment]
Sorry for the late response, yes I still have those issues. I have tried them on separate devices, separate android OS version and yet same issue. Here are the details:

I have used 3 devices in total:
- Nexus 7 (2012) rooted with ASOP 7.1.1 using Linux Deploy with Linux Kernal v3.4 (armhf)
- LG G6 on Android 7.0 using Gnuroot Debian with Kernal v3.18.31 (arm64)
- Samsung Galaxy S9+ on Android 8.0 using UserLAnd with Kernal v4.9.65 (arm64)

Now to detail the issues to these packages:
-Gmsh on both Debian 8 and 9 under proot exits with error: Segmentation Fault 
-Paraview and Blender on both Debian 8 and 9 causes shared library lib256.so 
-Scilab on Debian 8 and 9 shows a LIBEGL warning and then throws lots of Java exceptions before it terminates recursively.

Are these due to Proot limitations themselves or am I missing certain files?

**Comment by oxr463** [comment]
I'll have to see what I can find out and I'll get back to you on that. In the mean time, do you have any logs from any of these devices?

**Comment by oxr463** [comment]
This sounds like one of your issues: https://github.com/corbinlc/gnuroot/issues/99

**Comment by oxr463** [comment]
From what I can tell, it looks like these may be GNURoot issues. Also, that project appears to be abandoned. If I were you, I would try to maybe get a hold of the author (since he doesn't appear to be responding to any of the 80+ issues on that project).
