### ISSUE TITLE
Segmentation fault running mc2xml binary

### ISSUE THREAD

**Issue by ttblum** [proot-me/proot#142]
I'm running proot 5.1.0 bundled with GNURoot Debian, on Android TV Marshmallow, on a Wetek Play 2 (ARM).

I have shell root access to the Android TV OS, but it isn't 'rooted'.

I would like to run the 'mc2xml' application to update my TV listings.  A statically linked binary is available for it for ARM linux, but not for Android.  

If I run mc2xml using chroot, it runs fine:
```
# chroot /data/data/com.gnuroot.debian/debian /bin/bash -c "cd /root/; /root/mc2xml"
Update succeeded
```
But when I run it under proot it segfaults:
```
# /data/data/com.gnuroot.debian/support/proot -r /data/data/com.gnuroot.debian/debian /bin/bash -c "cd /root/; /root/mc2xml”
Segmentation fault

# /data/data/com.gnuroot.debian/support/proot -r /data/data/com.gnuroot.debian/debian /bin/bash
root@localhost:/root# ./mc2xml
Segmentation fault
```

Why is this binary throwing a segmentation fault under proot, but not under chroot?

uname on the host Android TV OS shows:
```
# uname -a
Linux localhost 3.14.29 #5 SMP PREEMPT Tue Aug 29 00:17:11 WEST 2017 armv8l
```

**Comment by oxr463** [comment]
Can you post the output from running `strace`?

**Comment by oxr463** [comment]
The website for that application does not contain any links for an ARM build so there really is no other way to reproduce this issue. I would recommend contacting the author of `mc2xml`.
