### ISSUE TITLE
Can't get response in java program

### ISSUE THREAD

**Issue by MisterGitHubber** [proot-me/proot#145]
I wrote script with PRoot usage. He works currectly in terminal emulator.

    #!/data/data/com.d330.veneraide/support/busybox sh

    PROOT_TMP_DIR=/data/data/com.d330.veneraide/support/ /data/data/com.d330.veneraide/support/proot -r /data/data/com.d330.veneraide/debian -v -1 -p -H -0 -l -L -b /sys -b /dev -b /proc -b /data -b /mnt -b /proc/mounts:/etc/mtab -b /:/host-rootfs /data/data/com.d330.veneraide/debian/opt/jdk1.8.0_181/bin/$@

And try run it from java code:

    runJavaCommand("java -version");

    public void runJavaCommand(String command) {
	try {
	    Process process = Runtime.getRuntime().exec("/data/data/com.d330.veneraide/support/java_command " + command);
	    BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
            int read;
	    char[] buffer = new char[4096];
	    StringBuffer output = new StringBuffer();
	    while ((read = reader.read(buffer)) > 0) {
		output.append(buffer, 0, read);
	    }
	    reader.close();
	    Toast.makeText(this, output.toString(), Toast.LENGTH_LONG).show();
	}
        catch (IOException e) {}
    }

But i get empty response. If i change command to "ls" my code works currectly and I see response in `Toast`. Why i get empty response? Maybe because the file system is changing?

**Comment by oxr463** [comment]
I noticed this is running on android; are you using the termux fork by any chance?

**Comment by oxr463** [comment]
@MisterGitHubber, are you still experiencing this issue?
