### ISSUE TITLE
Cannot readlink of proc/self/cwd

### ISSUE THREAD

**Issue by amenk** [proot-me/PRoot#151]
I am getting this error on a hosteurope managed server, what does that mean?

ftp1241457:~$ junest -f -p "-v 1"
proot info: binding = /dev
proot info: binding = /sys
proot info: binding = /proc
proot info: binding = /tmp
proot info: binding = /is/htdocs/wp12414575_0M9VC2TUSH
proot info: binding = /is/htdocs/wp12414575_0M9VC2TUSH/.junest:/
proot info: glue rootfs = /tmp/proot-25413-FZU4Tg
proot info: exe = /usr/bin/sh
proot info: argv = /bin/sh --login -c :
proot info: initial cwd = /is/htdocs/wp12414575_0M9VC2TUSH
proot info: verbose level = 1
proot info: pid 25414: terminated with signal 11
proot warning: can't readlink '/proc/self/cwd': Permission denied
proot info: binding = /dev
proot info: binding = /sys
proot info: binding = /proc
proot info: binding = /tmp
proot info: binding = /is/htdocs/wp12414575_0M9VC2TUSH
proot info: binding = /is/htdocs/wp12414575_0M9VC2TUSH/.junest:/
proot info: glue rootfs = /tmp/proot-25415-LhE9Bg
proot info: exe = /usr/bin/sh
proot info: argv = /bin/sh --login -c :
proot info: initial cwd = /is/htdocs/wp12414575_0M9VC2TUSH
proot info: verbose level = 1
proot info: pid 25417: terminated with signal 11
proot warning: can't readlink '/proc/self/cwd': Permission denied
Error: Something went wrong wüith proot command. Exiting

**Comment by oxr463** [comment]
```c
/* Sanity check: ensure the current directory lies in
	 * "/tmp".  */
	status = readlink("/proc/self/cwd", prefix, length_temp_directory);
	if (status < 0) {
		note(NULL, WARNING, SYSTEM, "can't readlink '/proc/self/cwd'");
		nb_errors++;
		goto end;
}
```
Taken from: [`src/path/temp.c`](https://github.com/proot-me/PRoot/blob/fb9503240eeaa3114b29b8742feb2bda6edccde8/src/path/temp.c#L102)

**Comment by amenk** [comment]
@oxr463 I am using the latest junest, which ships with proot 5.1.0

What is happening in the above function? cleaning temp? Can it be skipped by some env variable? is it important?

**Comment by oxr463** [comment]
Could you try setting `PROOT_TMP_DIR` in your environment to another location?

**Comment by amenk** [comment]
I did already --- I should have mentioned (but was thinḱing it might be in the debug output , sorry)
    cd
    mkdir tmp
    export PROOT_LOADER=.junest/opt/proot/proot-x86_64
    export PROOT_TMP_DIR=./tmp
    export PROOT_NO_SECCOMP=1

**Comment by amenk** [comment]
I am wondering if it is picking up those env variables, because I cannot see the $HOME/tmp in the debug output ...

proot still prints

     proot info: glue rootfs = /tmp/proot-25336-ImGCJc
