### ISSUE TITLE
Does PRoot work on MacOSX?

### ISSUE THREAD

**Issue by katakombi** [proot-me/PRoot#155]
Hi everyone,

 I am developing a Linux software which relies on proot, and checking whether I could make it available for MacOS. Does proot run already successfully under recent MacOSes?
If the answer is no, what would be necessary to be done?

thanks

**Comment by katakombi** [comment]
Thanks for the prompt answer! Though I knew about the ptrace dependency I recall having read that there exists ptrace implementations for FreeBSD/MacOSX as well. But then again I don't have too much expertise in that particular technical field.

**Comment by oxr463** [comment]
You're welcome! You are correct, there is a `ptrace` on other UNIX-like systems, however, without going into too much detail, most of the PRoot code-base has been written against Linux specifically. For now, myself and a few others are trying to improve the project as-is, but maybe in the far future, we may be able to make the code portable to other kernels.
