### ISSUE TITLE
cannot add new user due to pam not working inside proot

### ISSUE THREAD

**Issue by josch** [proot-me/proot#156]
Hi,

it is currently impossible to use `adduser` or `useradd` with proot on a system with pam. I found this problem when I tried installing systemd inside a Debian unstable proot session and I got this error during execution of the maintainer script:

```
chfn: PAM: System error
adduser: `/usr/bin/chfn -f systemd Time Synchronization systemd-timesync' returned error code 1. Exiting.
```

Similarly, trying to issue `adduser` fails as well like this:

```
$ adduser blub
Adding user `blub' ...
Adding new group `blub' (1002) ...
Adding new user `blub' (1002) with group `blub' ...
Creating home directory `/home/blub' ...
Copying files from `/etc/skel' ...
Enter new UNIX password: 
Retype new UNIX password: 
passwd: System error
passwd: password unchanged
Try again? [y/N] N
chfn: PAM: System error
adduser: `/usr/bin/chfn blub' returned error code 1. Exiting.
```

Or like this:

```
$ useradd anothertest
$ echo anothertest:test | chpasswd
chpasswd: (user anothertest) pam_chauthtok() failed, error:
System error
chpasswd: (line 1, user anothertest) password not changed
```

A workaround for this, is to add a fake `audit_log_acct_message` function via `LD_PRELOAD` as it is explained here by JH Chatenet:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=745082#75

So maybe the reason is similar as in that bug that was reported against fakechroot, that the problem is missing support for suid binaries?

In any case, it would be nice if proot would somehow allow pam to work so that scripts can make changes to /etc/shadow and friends accordingly without throwing an error.

Thanks!

**Comment by oxr463** [comment]
Have you tried using the __fake_id0__ extension ([1])?

> The fake_id0 extension can now fake any user and group identifiers. --[`doc/proot/changelog.txt`](https://github.com/proot-me/PRoot/blob/master/doc/proot/changelog.txt#L206)

[1]: https://github.com/proot-me/PRoot/blob/master/src/extension/fake_id0/fake_id0.c

**Comment by josch** [comment]
I did not! Do you have some runes for me how I could use the `-i` option to make pam and adduser work?

**Comment by oxr463** [comment]
Try the `-0`option, from the manual.

> Some programs will not work correctly if they are not run by the
"root" user, this is typically the case with package managers.  PRoot
can fake the root identity and its privileges when the ``-0`` (zero)
option is specified::

    proot -r /mnt/slackware-8.0/ -0
    
    # id
    uid=0(root) gid=0(root) [...]
    
    # mkdir /tmp/foo
    # chmod a-rwx /tmp/foo
    # echo 'I bypass file-system permissions.' > /tmp/foo/bar
    # cat /tmp/foo/bar
    I bypass file-system permissions.

--https://github.com/proot-me/PRoot/blob/master/doc/proot/manual.txt

**Comment by oxr463** [comment]
> Did you try running the commands I showed in my initial report?

Indeed.

**Host Info**

```terminal
uname -a
Linux dell-xps-13 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

sudo apt install -y proot

proot -V

 _____ _____              ___
|  __ \  __ \_____  _____|   |_
|   __/     /  _  \/  _  \    _|
|__|  |__|__\_____/\_____/\____| 5.1.0

built-in accelerators: process_vm = yes, seccomp_filter = no

Visit http://proot.me for help, bug reports, suggestions, patchs, ...
Copyright (C) 2014 STMicroelectronics, licensed under GPL v2 or later.
```

**Guest Rootfs**

```terminal
wget http://dl-cdn.alpinelinux.org/alpine/v3.8/releases/x86_64/alpine-minirootfs-3.8.2-x86_64.tar.gz

mkdir tmp && cd tmp

tar -xf ../alpine-minirootfs-3.8.2-x86_64.tar.gz

cp /etc/resolv.conf etc

proot -r . -0
proot warning: can't chdir("/home/lramage/repos/proot/tmp/./.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/
dell-xps-13:/#

# Add a user
adduser blub
New password:
Retype new password:
passwd: password updated successfully
dell-xps-13:/# ls /home/
blub
dell-xps-13:/# tail -n1 /etc/passwd
blub:x:1000:1000:Linux User,,,:/home/blub:/bin/bash

# Delete a user
deluser blub
deluser: can't find blub in /etc/group

# Shadow isn't installed by default in alpine
apk update && apk add shadow

# Add user again
# NOTE: option -m not specified, so $HOME directory not created.
useradd anothertest
Creating mailbox file: No such file or directory
tail -n1 /etc/passwd
anothertest:x:1000:1000::/home/anothertest:/bin/bash
echo anothertest:test | chpasswd
echo $?
0
```

**Comment by josch** [comment]
Right, but this is an alpine linux guest rootfs. Is alpine linux using pam? I observed the problem in a Debian unstable guest rootfs. Shall I prepare a rootfs tarball for you to?

**Comment by oxr463** [comment]
> Is alpine linux using pam?

Linux-PAM is a dependency of the shadow package ([1]), so yes, it is using PAM.

[1]: https://pkgs.alpinelinux.org/package/v3.8/community/x86_64/shadow

**Comment by josch** [comment]
And I can still reproduce it in a debian unstable chroot.

If you have debootstrap available, you can produce a chroot environment by doing:

    $ sudo debootstrap --variant=minbase unstable ./debian-unstable
    $ sudo chown -R josch:josch ./debian-unstable

And then reproduce the problem with:

    $ proot --rootfs=debian-unstable --root-id
    # apt update
    # apt install systemd-sysv --yes
    [...]
    chfn: PAM: System error
    adduser: `/bin/chfn -f systemd Time Synchronization systemd-timesync' returned error code 1. Exiting.
    [...]
    E: Sub-process /usr/bin/dpkg returned an error code (1)

Or simply by doing adduser:

    # adduser foo
    [...]
    Enter new UNIX password: 
    Retype new UNIX password: 
    passwd: System error
    passwd: password unchanged

If you don't have debootstrap available, I can also create you a tarball.

I'm running proot 5.1.0-1.3 from Debian unstable.

**Comment by oxr463** [comment]
Here is the full output from the first one:

```terminal
proot --rootfs=debian-unstable --root-id
proot warning: can't chdir("/home/lramage/repos/proot/tmp/./.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
# apt install systemd-sysv -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libnss-systemd
The following NEW packages will be installed:
  libnss-systemd systemd-sysv
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/293 kB of archives.
After this operation, 519 kB of additional disk space will be used.
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
debconf: delaying package configuration, since apt-utils is not installed
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
Setting up systemd (240-2) ...
chfn: PAM: System error
adduser: `/usr/bin/chfn -f systemd Network Management systemd-network' returned error code 1. Exiting.
dpkg: error processing package systemd (--configure):
 installed systemd package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 systemd
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

For this one, let's try another option from the man page,

> Instead, it is recommended to use
the ``-S`` option.  This latter enables the ``-0`` option and binds
only paths that are known to not be updated by packages...
--https://github.com/proot-me/PRoot/blob/master/doc/proot/manual.txt#L229

And here is the second:

```terminal
# adduser foo
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Adding user `foo' ...
Adding new group `foo' (1000) ...
Adding new user `foo' (1000) with group `foo' ...
Creating home directory `/home/foo' ...
Copying files from `/etc/skel' ...
Enter new UNIX password:
Retype new UNIX password:
passwd: System error
passwd: password unchanged
Try again? [y/N] n
chfn: PAM: System error
adduser: `/usr/bin/chfn foo' returned error code 1. Exiting.
# ls /home/
foo
# tail /etc/passwd
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
systemd-timesync:x:101:102::/run/systemd:/usr/sbin/nologin
systemd-network:x:102:103::/run/systemd:/usr/sbin/nologin
foo:x:1000:1000::/home/foo:/bin/bash
```

So the user is actually being created, despite the error.

**Comment by josch** [comment]
But the process still exits with a non-zero exit code.

Do you acknowledge that this is a bug or not?

**Comment by oxr463** [comment]
There is no doubt it's a bug, but since 1) this is only happening in Debian Unstable, and 2) there are unexplored options from the manual; I would like to narrow down what the actual issue is.

**Comment by josch** [comment]
Okay, wonderful! Yes, it's very weird that apparently only Debian is affected.

I'm very interested in this problem getting fixed, so I can allocate some time on this issue. What do you think would be some good next steps to narrow down this issue? Maybe I should try some other distributions to see if maybe Fedora or Arch are affected as well?

I never dived into the proot internals, but maybe I can figure out which syscall exactly is the culprit using some tracing?

Any other ideas on how we can get to the bottom of this?

**Comment by oxr463** [comment]
I would try Debian stable to see if it's just on unstable? Fedora and Arch might help too.

I'm actually one of the newest maintainers for PRoot, so I too am just learning more about 
the inner-workings of the code. But I would try to see if you could run PRoot in `gdb`?
Or perhaps `strace`?

I'm not really sure, but I will assist in anyway that I can.

**Comment by josch** [comment]
Okay, so here is a longer analysis. During all my tests I'm on Debian unstable. Just to make sure that this problem persists, I just compiled proot from git and I'm still getting:

    chfn: PAM: System error
    adduser: `/usr/bin/chfn testuser' returned error code 1. Exiting.

So this problem does not seem to be specific to the Debian package that I'm using but also persists in git still. Then I tested various chroots. I also tested alpine Linux to make sure that there is no systematic error in my tests but indeed it worked. My tests involved unpacking a rootfs tarball from https://images.linuxcontainers.org/images into a directory, then changing ownership to my own user, and then executing:

    $ proot --root-id --rootfs=./chroot-directory
    # useradd foobar
    # echo "foobar:complex_passphrase" | chpasswd
    chpasswd: (user foobar) pam_chauthtok() failed, error:
    System error
    chpasswd: (line 1, user foobar) password not changed
    # chfn foobar
    chfn: PAM: System error

Here are my results. The column "works" indicates, whether above problem appears or not.

works | system
--|--
:heavy_check_mark: | alpine minirootfs 3.8.2
:x: | debian unstable
:x: | debian stable
:x: | debian oldstable
:x: | ubuntu bionic
:x: | ubuntu xenial
:x: | ubuntu trusty
:heavy_check_mark: | gentoo 20190112_14:12
:heavy_check_mark: | arch linux 20190113_01:27
:heavy_check_mark: | centos 7
:heavy_check_mark: | fedora 29

So it seems that only Debian and derivatives are affected.

**Comment by oxr463** [comment]
Wow! That's really amazing! I'll take a look into the default PAM configuration on those systems to see how they differ.

**Comment by josch** [comment]
Or maybe there are some Debian-specific patches to adduser, shadow or pam that invoke this behaviour?

**Comment by oxr463** [comment]
Oh, yeah I didn't think of that.

**Comment by oxr463** [comment]
@josch, Greetings! Any progress on this?

**Comment by josch** [comment]
I'm currently on holidays and did not manage to look into this problem since my last post to this issue.

**Comment by oxr463** [comment]
No worries! Enjoy!

**Comment by oxr463** [comment]
@josch any word on this yet?

**Comment by josch** [comment]
Nope, I did not continue work on this as other stuff has priority for me right now.

But I hope I left enough information in this issue so that people with sufficient time and interest in proot can take a stab at figuring out what the problem is.

**Comment by oxr463** [comment]
Thanks for all the debugging you have put into this so far.

**Comment by oxr463** [comment]
@josch, it looks like [this](https://github.com/proot-me/proot/issues/174#issuecomment-495406815) might be the answer to this issue. If you have any time to test, let me know; otherwise, I can test it myself before closing this issue.

**Comment by josch** [comment]
I'm confused now. The message you link to lists DebianBug#745082 but I already pointed to this bug in the submission to this issue and noted that this is a workaround. So how is this news?

**Comment by eebssk1** [comment]
@josch well I think these issue are hard to resolve by modding proot?

**Comment by oxr463** [comment]
@josch, apologies, I didn't realize they were the same thing. 😳

**Comment by josch** [comment]
The problem is no more. I bisected Debian unstable to find out that the problem disappeared when pam 1.3.1-1 was uploaded at timestamp `2019-02-12 16:14:58+00:00` and replaced pam 1.1.8-4. So this indeed seems to have been some pam problem and some change in pam from 1.1.8 to 1.3.1 fixed the issue.
