### ISSUE TITLE
Unable to extract loader from binary on runtime (SIGILL)

### ISSUE THREAD

**Issue by dan-santana** [proot-me/PRoot#158]
I'm trying to port PRoot to Alpine Linux (musl-based distro), but it's receiving a SIGILL during the  `extract_loader()` call at the following line when trying to read the binary loader from memory:
 https://github.com/proot-me/PRoot/blob/11972c0dab34e088c55c16a94d26c399ca7a26d8/src/execve/enter.c#L499

Here's the output of `proot -v 10 -S /home/user/my_root busybox.static ls`: 
```
proot info: binding = /home/user/my_root
proot info: binding = /home/user
proot info: binding = /tmp
proot info: binding = /proc
proot info: binding = /sys
proot info: binding = /dev
proot info: binding = /etc/resolv.conf
proot info: binding = /etc/hosts
proot info: binding = /home/user/my_root:/
proot info: vpid 1: translate("/home/user/projects/terapixel/proot" + "busybox.static")
proot info: vpid 1:          -> "/home/user/projects/terapixel/proot/busybox.static"
proot info: vpid 1: translate("/" + "/usr/sbin/busybox.static")
proot info: vpid 1:          -> "/home/user/my_root/usr/sbin/busybox.static"
proot info: vpid 1: translate("/" + "/usr/bin/busybox.static")
proot info: vpid 1:          -> "/home/user/my_root/usr/bin/busybox.static"
proot info: vpid 1: translate("/" + "/sbin/busybox.static")
proot info: vpid 1:          -> "/home/user/my_root/sbin/busybox.static"
proot info: vpid 1: translate("/" + "/bin/busybox.static")
proot info: vpid 1:          -> "/home/user/my_root/bin/busybox.static"
proot info: vpid 1: translate("/" + "/bin/busybox.static")
proot info: vpid 1:          -> "/home/user/my_root/bin/busybox.static"
proot info: exe = /bin/busybox.static
proot info: argv = busybox.static ls
proot info: initial cwd = /home/user/projects/terapixel/proot
proot info: verbose level = 10
proot info: pid 12304: access to "/dev/pts/4" (fd 0) won't be translated until closed
proot info: pid 12304: access to "/dev/pts/4" (fd 1) won't be translated until closed
proot info: pid 12304: access to "/dev/pts/4" (fd 2) won't be translated until closed
proot info: pid 12304: access to "/proc/12304/fd" (fd 3) won't be translated until closed
proot info: ptrace acceleration (seccomp mode 2) enabled
proot info: vpid 1: sysenter start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x20) = 0xffffffffffffffda [0x7ffdb661d8e0, 0]
proot info: vpid 1: sysenter end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x20) = 0xffffffffffffffda [0x7ffdb661d8e0, 0]
proot info: vpid 1: sysexit start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x20) = 0x0 [0x7ffdb661d8e0, 0]
proot info: vpid 1: sysexit end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x20) = 0x0 [0x7ffdb661d8e0, 0]
proot info: vpid 1: sysenter start: execve(0x7fcba3e14e80, 0x7ffdb661db60, 0x7ffdb661db78, 0x7fcba3e36600, 0xfefefefefefefeff, 0x8080808080808080) = 0xffffffffffffffda [0x7ffdb661d9b0, 0]
proot info: vpid 1: translate("/" + "/bin/busybox.static")
proot info: vpid 1:          -> "/home/user/my_root/bin/busybox.static"
proot warning: signal 4 received from process -1344915502
```
It works perfectly when passing `$PROOT_LOADER` pointing to the built `loader` binary file.

**Comment by dan-santana** [comment]
Note that I'm able to cross-compile to x86-64 musl from Void Linux (x86-64 glibc) and the resulting `proot` binary doesn't present this issue when running it on Alpine Linux. The build process is the same, so I currently have no clue on what's going wrong on the `proot` binary built directly on Alpine Linux.

**Comment by oxr463** [comment]
Greetings,

I already have an aport for Alpine (See: https://gitlab.com/oxr463/aports/issues/18), however there are a few issues remaining before it can be submitted.

About a month or so ago, I merged a pull request for musl support, and I also emailed some of the other aports maintainers (specifically the one for libtalloc), about including static libraries for the purpose of rebasing our ci on Alpine/Docker instead of Slackware and the current build scripts (See proot static repository).

**Comment by dan-santana** [comment]
Awesome! I was going to make a PR with the libtalloc.a fix + PRoot package after loader issue was solved, but it seems you are one step ahead of me :)

I'll try building with your PKGBUILD to see if the bug still happens and I'll post any updates here.

**Comment by dan-santana** [comment]
Unfortunately [this APKBUILD](https://gitlab.com/oxr463/aports/issues/18#note_101216083) seems to not be building properly here (the `care` build is failing + `tracee.h` reporting incomplete type on `restart_how`), so in any case here's my APKBUILD:
```sh
# Contributor: Daniel Santana <daniel@santana.tech>
# Maintainer: Daniel Santana <daniel@santana.tech>
pkgname=proot
_pkgname=PRoot
pkgver=5.1.0_git20190206
_sha=11972c0dab34e088c55c16a94d26c399ca7a26d8 # contain musl fixes
pkgrel=0
pkgdesc="User-space implementation of chroot, mount --bind, and binfmt_misc"
url="https://proot-me.github.io"
arch="all"
license="GPL-2-or-later"
makedepends="bsd-compat-headers linux-headers libarchive-dev talloc-dev"
subpackages="$pkgname-doc $pkgname-static"
source="$_pkgname-$pkgver.tar.gz::https://github.com/proot-me/PRoot/archive/$_sha.tar.gz"
builddir="$srcdir/$_pkgname-$_sha"
options="!check" # several tests are failing

build() {
	cd "$builddir"/src

	make LDFLAGS="$LDFLAGS -ltalloc -static"
	mv proot proot.static
	make LDFLAGS="$LDFLAGS -ltalloc"
}

package() {
	install -Dm 0755 "$builddir"/src/proot "$pkgdir"/usr/bin/proot
	install -Dm 0644 "$builddir"/doc/proot/man.1 "$pkgdir"/usr/share/man/man1/proot.1
}

static() {
	install -Dm 0755 "$builddir"/src/proot.static "$subpkgdir"/usr/bin/proot.static
}

sha512sums="728ba3ce1e0de570b8d3e7f6335602eaea09b58a6707e25a834de7d56432982d6d223f0af297197060249350a3143209d3b74916eb5afb94e4a2dfe1a8bd2f0a  PRoot-5.1.0_git20190206.tar.gz"
```

It also includes a `proot-static` build that I'm currently in need to automate some tasks. The only piece that is missing to build it is the `libtalloc.a` that I added to `talloc-dev` in a private repository.

Am I missing something that might be causing the `extract_loader` error?

**Comment by oxr463** [comment]
Hmm, I'm not sure then. I'll have to look into this further. 

If you could, it would be great to have that patch for `talloc-dev` submitted upstream.

**Comment by dan-santana** [comment]
Patch submitted :) https://patchwork.alpinelinux.org/patch/4489/

**Comment by oxr463** [comment]
@dan-santana, I reached out on `#alpine-devel` to see if we can get your patch pushed.

In the meantime, I'm closing out my issue for creating a PRoot aport (https://gitlab.com/oxr463/aports/issues/18), in favor of letting you figure it out; this way, I can concentrate efforts elsewhere.

**Comment by dan-santana** [comment]
FYI: The libtalloc.a patch was upstreamed today and is already on the repositories :) Now this issue is the only thing left before adding PRoot to Alpine Linux :tada:

**Comment by dan-santana** [comment]
Update: I can replicate the bug with the following minimal example:
```c
#include <stdio.h>
#include <unistd.h>
#include <sys/stat.h>

extern unsigned char  _binary__bin_busybox_start;
extern unsigned char  _binary__bin_busybox_end;

int main(int argc, char *const argv[])
{
  void *start = (int *) &_binary__bin_busybox_start;
  size_t size = (size_t)(&_binary__bin_busybox_end - &_binary__bin_busybox_start);
  FILE *file = fopen("/tmp/busybox", "wb");
  int fd = fileno(file);
  write(fd, start, size);
  fchmod(fd, S_IRUSR | S_IWUSR | S_IXUSR);
  fclose(file);
  return 0;
}
```
And compiling in the following way:
```
objcopy --input-target binary --output-target elf64-x86-64 --binary-architecture i386:x86-64 /bin/busybox busybox.o
gcc -o app main.c busybox.o
```

In this way it works with both glibc and musl, but when I compile with the `-O2` flag I receive a `SIGILL` on the `write` call when running `./app`. This bug only happens in the optimized builds with musl, while on glibc it still works perfectly.

**Comment by awilfox** [comment]
Alpine uses "standalone `fortify-headers`" which emit `SIGILL`, and is disabled with -O0 but enabled with -O2.

In their private copy of [`write`](https://git.2f30.org/fortify-headers/file/include/unistd.h.html#l146):

```c
_FORTIFY_FN(write) ssize_t write(int __f, const void *__s, size_t __n)
{
	size_t __b = __builtin_object_size(__s, 0);
 
	if (__n > __b)
		__builtin_trap();
	return __orig_write(__f, __s, __n);
}
```

Since the compiler does not know how big `start` is, this comparison fails and you crash.

**Comment by richfelker** [comment]
It does know how big start is: it's 1 byte, because that's how you declared it. Instead of:

```
extern unsigned char  _binary__bin_busybox_start;
extern unsigned char  _binary__bin_busybox_end;
```

try:

```
extern unsigned char  _binary__bin_busybox_start[];
extern unsigned char  _binary__bin_busybox_end[];
```

then remove the `&` (address-of) operators in the code below.

**Comment by oxr463** [comment]
@awilfox, how can we disable it?

**Comment by dan-santana** [comment]
@oxr463 I'm preparing a PR right now :)
