### ISSUE TITLE
Proot may not support MediaTek's helio A22 cpu

### ISSUE THREAD

**Issue by sunshinewithmoonlight** [proot-me/PRoot#160]
I refer to the guide :
https://wiki.termux.com/wiki/Proot

When trying to proot, I get the following error:
root info: vpid 1: terminated with signal 11

I think that proot may not support MediaTek's helio A22 cpu till now. Right?

**Comment by sunshinewithmoonlight** [comment]
The phone is Redmi 6A with MTK Helio A22 and Android 8.1 .

$ ./start-ubuntu.sh
proot info: vpid 1: terminated with signal 11

$ uname -a
Linux localhost 4.9.77+ #1 SMP PREEMPT Sat Dec 29 16:31:02 CST 2018 armv7l Android


Other things to say:
I have used redmi 4. It uses the Snapdragon 425 cpu and can run proot. The helio a22 is said to have been designed to counter the cpu of the Snapdragon 400 series. However, the instruction set of helio a22 may not be doing very well.

**Comment by oxr463** [comment]
Greetings,

Termux has their own fork of PRoot (https://github.com/termux/proot), which has changes that have not been merged upstream here yet (See: https://github.com/termux/proot/issues/22). If you are having an issue with the Termux variant, I suggest that you open an issue there first.

Alternatively, you could try downloading a static PRoot (https://github.com/proot-me/proot-static-build/tree/master/static), and testing with that. Keep in mind, that the latest builds are anywhere from 4 - 6 years old.

Cheers,

**Comment by sunshinewithmoonlight** [comment]
> Greetings,
> 
> Termux has their own fork of PRoot (https://github.com/termux/proot), which has changes that have not been merged upstream here yet (See: [termux/proot#22](https://github.com/termux/proot/issues/22)). If you are having an issue with the Termux variant, I suggest that you open an issue there first.
> 
> Alternatively, you could try downloading a static PRoot (https://github.com/proot-me/proot-static-build/tree/master/static), and testing with that. Keep in mind, that the latest builds are anywhere from 4 - 6 years old (See: #127).
> 
> Cheers,

Well, thank you very much.

**Comment by sunshinewithmoonlight** [comment]
I think I need to add the end of the story.

I used magicsk and chroot and linux deploy to solve this problem.

And now, I can use julia language on Android 8. Cheers!

**Comment by oxr463** [comment]
Awesome, glad to hear it!
