### ISSUE TITLE
Add Void Linux to Ecosystem

### ISSUE THREAD

**Issue by oxr463** [proot-me/proot#175]
Void Linux uses PRoot for its `xbps-src` utility:

> xbps-src supports multiple utilities to accomplish this task:
> - proot(1) - utility that implements chroot/bind mounts in user space, see https://proot-me.github.io/. --https://github.com/void-linux/void-packages

Void Linux also provides a package for PRoot:

- https://github.com/void-linux/void-packages/tree/master/srcpkgs/proot

**Comment by chazanov** [comment]
@oxr463 In my dockerfile the compilation of proot always fails.
```
=> proot-5.1.0_5: installing target dependency 'libarchive-devel-3.3.3_3' ...
=> proot-5.1.0_5: installing target dependency 'talloc-devel-2.1.14_1' ...
=> proot-5.1.0_5: running do-fetch hook: 00-distfiles ...
=> proot-5.1.0_5: fetching distfile 'v5.1.0.tar.gz'...
looking up github.com
connecting to github.com:443
SSL options: 4004
Peer verification enabled
Using CA cert path: /etc/ssl/certs
Verify hostname
[TLS]
requesting https://github.com/proot-me/PRoot/archive/v5.1.0.tar.gz
302 redirect to https://codeload.github.com/proot-me/proot/tar.gz/v5.1.0
looking up codeload.github.com
[SSL/TLS]
requesting https://codeload.github.com/proot-me/proot/tar.gz/v5.1.0
v5.1.0.tar.gz: [0B 0%] 308KB/s ETA: unknown
v5.1.0.tar.gz: [0B 0%] 112KB/s ETA: unknown
v5.1.0.tar.gz: 247KB [avg rate: 2308KB/s]
=> proot-5.1.0_5: verifying checksum for distfile 'v5.1.0.tar.gz'... 
=> ERROR: SHA256 mismatch for 'v5.1.0.tar.gz:'
ce0a3baca8312613bd10f65bb436a3aaa28e1034f498a22c35ad0693600e01dd
=> ERROR: proot-5.1.0_5: couldn't verify distfiles, exiting...
```
May you please fix this?

**Comment by oxr463** [comment]
I'm assuming that since you are commenting on this ticket, that you are trying to install PRoot on Void Linux, correct?

If so, you will need to reach out to the package maintainer for help. At the very least, it appears that he will need to update the sha256sum used in his package recipe.
