### ISSUE TITLE
Document the location of static-binaries from GitLab CI/CD jobs

### ISSUE THREAD

**Issue by maralorn** [proot-me/proot#176]
## Expected Behavior

Since `proot` master seems to contain some important bug-fixes I am especially aiming at hoping for 09a0c3cd83c20ff680f6481ca1050bc1108d0363 I was wondering if you could provide newer static-compiled binaries.

This is a revival of #120, where the binaries were updated the last time.

I am on nix and had sadly no luck with compiling `proot` statically on my own.
I would be glad if you could either provide documentation how to do it or just provide the binaries.

## Actual Behavior

The newest static binaries I can find are from 2016 in the now archived [proot-static-build](https://github.com/proot-me/proot-static-build/releases) repo.
#120 also mentions other binaries in a comment which are from 2014.

## Steps to Reproduce the Problem

  1. Search the web for current statically linked  `proot` binaries.
  2. Can’t find any.

Thank you for your attention and working on `proot`!

**Comment by oxr463** [comment]
Greetings,

Development builds can be found under artifacts for GitLab CI/CD Pipelines:

- https://gitlab.com/proot/proot/pipelines

Here is the latest build on master:

- https://gitlab.com/proot/proot/-/jobs/210727458/artifacts/file/public/bin/proot

Hopefully that helps

**Comment by maralorn** [comment]
Wow, thank you so much. That helped!

**Comment by oxr463** [comment]
TODO

- [ ] Update documentation regarding compiling static binaries

```terminal
make -C src loader.exe loader-m32.exe build.h
LDFLAGS="${LDFLAGS} -static" make -C proot
```
