### ISSUE TITLE
Release tarball has changed?

### ISSUE THREAD

**Issue by jschultz** [proot-me/proot#178]
Sometime in the last few months the source [tarball](https://github.com/proot-me/proot/archive/v5.1.0.tar.gz) seems to have changed. I first noticed it when [void-linux](https://github.com/void-linux/void-packages) build script failed with a checksum error. It seems that the top level directory within the tarball has changed from PRoot to proot. Other than that everything is as it was.

This is strange behaviour for a release that is 5 years old. A bug in github perhaps?

**Comment by oxr463** [comment]
Possibly? The repository was renamed from PRoot to proot, but the old release files haven't been touched.

Hopefully we'll have another release here some time soon.

**Comment by jschultz** [comment]
It looks like even old release files get changed to reflect the change of repository name. I guess downstream users will just have to adapt.

Looking forward to the new release!

**Comment by oxr463** [comment]
Ah, that's interesting.

Glad to hear it!
