### ISSUE TITLE
Proot bug, No Disros Work

### ISSUE THREAD

**Issue by Kilo-411** [proot-me/proot#179]
$#76 port PROOT_NO_SECCOMP=1
$ ./start-debian.sh
bash: xmalloc: .././shell.c:1709: cannot allocate 10 bytes (0 bytes allocated)ll

  - Proot/Care version:
  - Kernel version:
  - Host distribution:
  - Guest distribution:

## Command Output

```terminal Termux .. No style will load API or Widgets 

$ ./start-debian.sh
proot info: vpid 1: terminated with signal 11

;proot error: 'gdb' not found (root = /, cwd = /data/data/com.termux/files/home, $PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets)
fatal error: see `proot --help`.
$ GNU gdb (GDB) 7.8


Im getting errors everywhere

**Comment by oxr463** [comment]
Greetings,

It appears that you are using the termux version of PRoot; as such, this issue should really be opened there, https://github.com/termux/proot/issues

**Comment by oxr463** [comment]
See also: https://github.com/proot-me/proot/issues/106
