### ISSUE TITLE
( Proot vpid error 11 )

### ISSUE THREAD

**Issue by ic3-chillz** [proot-me/proot#180]
## at the very first it 
.
$ ./start-debian.sh 
$ proot vpid error 11. ; its not letting other script either

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Proot/Care version:
  - Kernel version:
  - Host distribution:
  - Guest distribution:

#176 

```terminal
Inline log
```

-OR-

[Attached log]()

**Comment by oxr463** [comment]
Can you please provide more information? The issue template contains all the fields required. If you need any help gathering this, let me know.

**Comment by ic3-chillz** [comment]
All the distro does this. I also get other error



$ ./start-backbox.sh
proot info: vpid 1: terminated with signal 11



$ ./start-ubuntu.sh
proot info: vpid 1: terminated with signal 7      $

**Comment by oxr463** [comment]
What are the scripts doing? How is PRoot being invoked?

**Comment by ic3-chillz** [comment]
Export SECCOM 1st then i tried to make file .
. i really dont know im trying anything related to my issue

**Comment by oxr463** [comment]
Can you upload your scripts that you are trying to run?

**Comment by oxr463** [comment]
Closing in favor of https://github.com/proot-me/proot/issues/190
