### ISSUE TITLE
Implement vagrant for kernel-specific testing

### ISSUE THREAD

**Issue by oxr463** [proot-me/proot#194]
> Create tests for seccomp:
> - with PROOT_NO_SECCOMP
> - without PROOT_NO_SECCOMP
> - kernel version >= 4.8
> - kernel version < 4.8

_Originally posted by @oxr463 in https://github.com/proot-me/proot/issues/111#issuecomment-556226326_

See: https://github.com/OpenVPN/openvpn/pull/45

**Comment by eredisg** [comment]
I will take up this issue. According to @oxr463 via our private chat, we will want to implement CentOS, Debian, and Alpine vagrant boxes to start off with. 

Please see: https://www.vagrantup.com/docs/virtualbox/boxes.html

**Comment by oxr463** [comment]
@eredisg any progress on this one?

**Comment by oxr463** [comment]
We do not need to create the base boxes, just use these:

- [ ] Alpine
- [ ] [CentOS](https://app.vagrantup.com/centos)
- [ ] [Debian](https://app.vagrantup.com/debian)

I also created this: https://app.vagrantup.com/proot-me.

**Comment by oxr463** [comment]
See also: https://blog.centos.org/2019/07/updated-centos-vagrant-images-available-v1905-01/

**Comment by oxr463** [comment]
Requires installing the following plugin:

- [vagrant-sshfs](https://github.com/dustymabe/vagrant-sshfs#getting-started)

**Comment by oxr463** [comment]
Mapping out specific dependencies across distributions, (See: https://github.com/proot-me/blog/blob/master/drafts/dependencies.md).
