### ISSUE TITLE
Why it doesn't work

### ISSUE THREAD

**Issue by seisdr** [proot-me/proot#197]
![70534197-94325a80-1b6b-11ea-9a38-abbe9d5df2e8](https://user-images.githubusercontent.com/45742462/70546461-61df2800-1b80-11ea-9753-9b9db3f48125.png)
![70534209-9a283b80-1b6b-11ea-88d7-aba30198f0c3](https://user-images.githubusercontent.com/45742462/70546476-660b4580-1b80-11ea-8b6d-724cb5b50202.png)

**Comment by rschutt** [comment]
Probably due to https://github.com/proot-me/proot/issues/106.  What is your kernel version?

**Comment by seisdr** [comment]
```
$ uname -a
Linux localhost 3.10.86-g0c14827 #2 SMP PREEMPT Thu Jul 12 13:13:34 CST 2018 aarch64 Android
$ uname -a
```
Well the /bin/bash didn't work ..

**Comment by oxr463** [comment]
Hello,

You already posted to the correct project here, https://github.com/termux/proot/issues/85; the Termux fork has diverged a bit from here, and contains android-specific fixes.
