### ISSUE TITLE
Add "Compiling" section to the README

### ISSUE THREAD

**Issue by eredisg** [proot-me/proot#200]
A "Compiling" section should be added to the README to help guide new users and to make sure it is being installed correctly.

**Comment by oxr463** [comment]
The following command can be used to compile PRoot and CARE:

```sh
make -C src loader.exe loader-m32.exe build.h # first build the config and loader
make -C src proot care # then compile PRoot and CARE
make -C tests # Run test suite
```

**Comment by eredisg** [comment]
Thank you!
