### ISSUE TITLE
proot detection

### ISSUE THREAD

**Issue by cdown** [proot-me/proot#217]
Hi there,

I work on the systemd project, and as of recently am also a proot user. I'm wanting to add proot detection to `systemd-detect-virt`, which despite the name also detects various forms of containerisation and chrooting. Currently it doesn't detect anything inside a proot:

```
% systemd-detect-virt
none
```

What's the recommended way to detect a prooted container, as opposed to say, a chrooted container? I notice that some of your downstream users leave traces to make it obvious (like junest, which exports `JUNEST_ENV=1` to children), but I didn't find anything similar in proot itself.

Other methods I can think of aren't clear enough to identify proot vs. some other solution.

Any suggestions? :-)

**Comment by oxr463** [comment]
> What's the recommended way to detect a prooted container, as opposed to say, a chrooted container?

I don't think container is the right terminology here.

> I notice that some of your downstream users leave traces to make it obvious (like junest, which exports JUNEST_ENV=1 to children), but I didn't find anything similar in proot itself.

That's a good question!

Here are some questions for you:

- What are the benefits of providing such a feature?
- What are some standard methods used by other projects?
- Would you be willing to submit a PR for us? 😄

I think it should work similar to how `chroot` works now, (See: https://www.freedesktop.org/software/systemd/man/systemd-detect-virt.html#-r).

**Comment by cdown** [comment]
> I don't think container is the right terminology here.

Well, "container" as terminology is meaningless anyway, since it could mean just about anything ;-)

What terminology is more accurate in your eyes? Just "proot"?

> What are the benefits of providing such a feature?

One for me is that I can conditionally do things based on whether I am in proot or not. At its most basic, I might choose to indicate that I am in a different environment in my shell prompt. I may also choose to take some different actions in scripts or programs dependent on that execution environment.

(Lennart goes over some of the design decisions and uses of systemd-detect-virt here, although mostly in the abstract: http://0pointer.de/blog/projects/detect-virt.html)

> What are some standard methods used by other projects?

- For VMs, we usually use the cpuid, or `/proc/device-tree/hypervisor/compatible`. We can also use DMI information and some other tricks.
- For containers, we detect certain container types (eg. OpenVZ) dependent on the environment they provide (for example, `/proc/vz`). For others, we look at /proc/1/sched (which shows non-namespaced pids, but since proot doesn't namespace, this doesn't apply). We also have a few tricks for other cases like WSL.
- For chroot, we look at `/proc/1/root` vs. our root, but this doesn't work for unprivileged users, since `/proc/1/root` is EPERM.

I suspect the most reasonable path to take, if you're amenable, is to emulate a file called `/proc/proot`, with what it contains being immaterial. That way we don't pollute the environment of every application, and it has no passive cost.

> Would you be willing to submit a PR for us?

Of course! I'm interested in using this feature, so I also have a reason to want to see it through :-)

**Comment by oxr463** [comment]
Let's do the `/proc/proot` approach. I think it makes sense.

**Comment by cdown** [comment]
Great! I'll submit a PR soon, thanks for taking a look :-)

**Comment by cdown** [comment]
I just thought that we could probably do this transparently using `TracerPid`. What do you think about something like this?

https://github.com/cdown/systemd/commit/26610095b8394e1fd70af06233dd07a9ca55dc70

**Comment by oxr463** [comment]
> I just thought that we could probably do this transparently using `TracerPid`. What do you think about something like this?
> 
> [cdown/systemd@2661009](https://github.com/cdown/systemd/commit/26610095b8394e1fd70af06233dd07a9ca55dc70)
> 
> ```
> % build/systemd-detect-virt
> none
> % ~/git/proot/src/proot build/systemd-detect-virt
> proot
> ```

Looks good to me!

**Comment by cdown** [comment]
Great! I'll submit systemd PR now, and we can keep this open for tracking if you like.

**Comment by cdown** [comment]
Hey, how would you like this to be referred to in the documentation? Here are some examples from others:

```
          <row>
            <entry><varname>acrn</varname></entry>
            <entry><ulink url="https://projectacrn.org">ACRN hypervisor</ulink></entry>
          </row>

          <row>
            <entry valign="top" morerows="7">Container</entry>
            <entry><varname>openvz</varname></entry>
            <entry>OpenVZ/Virtuozzo</entry>
          </row>

          <row>
            <entry><varname>lxc</varname></entry>
            <entry>Linux container implementation by LXC</entry>
          </row>
```

**Comment by oxr463** [comment]
> -r, --chroot
>
>    Detect whether invoked in a chroot(2) environment. In this mode, no output is written, but the return value indicates whether the process was invoked in a chroot() environment or not.

I think this one matches the best.

Otherwise,

```
<row>
  <entry><varname>proot</varname></entry>
  <entry>chroot, mount --bind, and binfmt_misc without privilege/setup for Linux</entry>
</row>
```

**Comment by cdown** [comment]
`-r` isn't possible right now for... reasons (chroot mode basically only does one thing and requires root, which defeats the point of proot), let's stick with container for now. We already use it as a bucket for "not-quite-a-container" stuff like WSL, so I don't think it's dissonant with the context.

**Comment by oxr463** [comment]
@cdown Okay, sounds good!

**Comment by cdown** [comment]
@oxr463 I think I edited the suggested doc after you commented, can you eyeball it? :-)

**Comment by oxr463** [comment]
> 
> 
> @oxr463 I think I edited the suggested doc after you commented, can you eyeball it? :-)

Can you send the link? The site is still the same.

**Comment by cdown** [comment]
Oh, I just mean this suggested snippet:

```
<row>
  <entry><varname>proot</varname></entry>
  <entry><ulink url="https://proot-me.github.io/">proot</ulink> user-space chroot/bind mount emulation</entry>
</row>
```

**Comment by sudomain** [comment]
Unrelated to the systemd issue, but posting this here because this is one of the top search engine results for `detect if in "proot"`:

pgrep has a `--session` option and when `pgrep --session 0` is used it finds processes of the current session. Therefor, `pgrep --session 0 proot` will find proot processes running in the current session.
