### ISSUE TITLE
Is it possible to have real superuser access on PRoot?

### ISSUE THREAD

**Issue by krugerheadshot** [proot-me/proot#223]
Hi Dev and PRoot Users!

I was wondering if we can use real root access on PRoot because a few programs, no matter what, require superuser access.Of course fakeroot can come into play but this just doesn't work then! You can't use tools like Wireshark to their full extent!

I have seen an option to use real root in PRoot on AnLinux which installs the PRoot of several distros on Termux. I am using an old app "GNURoot" which also uses PRoot.

If what I am asking is possible then please tell me how to do so or if there's an ongoing project or research regarding this then please let me know!

Thank you!

**Comment by bew** [comment]
Why do you want to use proot then if you can have the normal root tools?

**Comment by krugerheadshot** [comment]
> Why do you want to use proot then if you can have the normal root tools?

Because I am using an old x86 Android 4.4.2 tablet which doesn't got much support from almost no develovers except Corbin Champion. I use Termux on my phone but I can't use it on my tablet which is what I wanted. PRoot is like a sandbox. I am also unable to use Linux Deploy or Complete Linux Installer on my tablet which could have run the Chroot.

Now I have no choice but to get real root access on GNURoot Wheezy which is my last bet!

**Comment by oxr463** [comment]
This is out of scope for PRoot. The whole purpose of the tool is to grant the ability for unprivileged setup for `chroot`,

> chroot, mount --bind, and binfmt_misc without privilege/setup for Linux

If you need support for trying to figure out how to use PRoot then feel free to either open a new issue with more details regarding any errors you are experiencing, or join our Gitter channel if you would like to chat.
