### ISSUE TITLE
Fatal error in Ubuntu and Debian

### ISSUE THREAD

**Issue by Flytreels** [proot-me/proot#229]
## Actual Behavior
Unlimited errors when installing packages using apt:proot warning: unknown syscall 278

Running Ubuntu apt without ROOT gives an error: root@localhost:/root# neofetch
 proot warning: unknown syscall 278

## Specifications

  - Proot/Care version: 5.1.1-static
  - Kernel version: 3.10

**Comment by penn5** [comment]
What architecture are you running on?

**Comment by Flytreels** [comment]
arm64

**Comment by Flytreels** [comment]
> What architecture are you running on?
arm64
