### ISSUE TITLE
Unable to start ssh service

### ISSUE THREAD

**Issue by Flytreels** [proot-me/proot#231]
## Actual Behavior

Unable to start SSH service, error
 proot warning: unknown syscall 278
....
## Specifications

  - Proot/Care version: 5.1
  - Kernel version: 3.10
  - OS: Android 9 arm64

## Command Output

```terminal
 -Loading

 sshd::start...
 mkdir: can't create directory'/var/run/sshd': File exists
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
 proot warning: unknown syscall 278
```

-OR-

[Attached log]()

**Comment by oxr463** [comment]
@Flytreels greetings! Are you using a version of PRoot that you have compiled yourself, i.e., from this repository? Or are you using the Termux fork? If so then you should file this issue at, github.com/termux/proot/issues.

**Comment by Flytreels** [comment]
Official static version

**Comment by oxr463** [comment]
https://github.com/proot-me/proot/blob/master/src/syscall/sysnums-x86_64.h#L282

https://github.com/proot-me/proot/blob/master/src/syscall/sysnums-arm64.h

**Comment by Flytreels** [comment]
yes
