### ISSUE TITLE
Where to find static builds for various platforms

### ISSUE THREAD

**Issue by DavHau** [proot-me/proot#239]
As stated on the [downlaods section of the website](https://proot-me.github.io/#downloads), the static builds found on https://github.com/proot-me/proot-static-build/releases are outdated.

As an alternative it states: https://gitlab.com/proot/proot/pipelines

But it seems like the gitlab pipeline only builds for x86_64.
Where can I find builds for other platforms?

All of that wouldn't be too much of an issue if there existed some reproducible build instructions. But those, I couldn't find as well.
I have been trying to statically build the most recent revision (ab43a25e35586b860d73d11da4c0076e6fe2b427) using nix. But as soon as I execute that proot binary inside a debian docker container, it raises:

```
# /proot true
proot error: execve("/bin/true"): Bad address
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.

```

**Comment by oxr463** [comment]
See: https://github.com/proot-me/proot/blob/master/doc/howto-release.rst

There is a section on static binaries.

**Comment by DavHau** [comment]
Thanks for the link.
Does that mean that proot maintainers are not interested in providing various builds themselves?
It would be nice to have something similar to https://github.com/proot-me/proot-static-build which is constantly updated.

One can find static builds on some package systems like alpine. But those often seem to only for for the specific distro. If I run this on debian, it crashes with the above error.
If there were builds provided by proot which actually work across platforms, that would make the project a lot more user friendly.

**Comment by oxr463** [comment]
@DavHau Not at this time. Perhaps this issue can serve as a placeholder to add previous versions to the corresponding GitHub release.

I was very involved with the alpine package, since I'm a package maintainer for that distribution as well. The debian package is old. If you are on Android, I would try the termux fork, since they have binary packages for ARM variants.

This project needs serious help. Providing binary package is low on the list of priorities at the moment.

**Comment by nathanshearer** [comment]
So that documentation on building static binaries is nice, but what kind of an environment should this be run under? I tried Gentoo linux, but a static version of talloc is not in the repository.

```
/tmp/proot-5.2.0-alpha $ LDFLAGS="${LDFLAGS} -static" make -C src proot
make: Entering directory '/tmp/proot-5.2.0-alpha/src'
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
  LD    proot
/usr/lib/gcc/aarch64-unknown-linux-gnu/9.3.0/../../../../aarch64-unknown-linux-gnu/bin/ld: cannot find -ltalloc
collect2: error: ld returned 1 exit status
make: *** [GNUmakefile:179: proot] Error 1
make: Leaving directory '/tmp/proot-5.2.0-alpha/src'
```

Should I prop up an entire Ubuntu vm? Or something else?

**Comment by oxr463** [comment]
You could use Ubuntu if you like.

Here is a blog post about static aarch64 binaries from Alpine, https://github.com/proot-me/blog/blob/master/posts/alpine-aarch64.md

**Comment by nathanshearer** [comment]
Thanks, I finally managed to get static binaries for aarch64 arm64 compiled. Steps for Ubuntu are below:

**Setup a working aarch64 arm64 environment**
Such as: https://cdimage.ubuntu.com/releases/20.04.2.0/release/ubuntu-20.04.2-preinstalled-server-armhf+raspi.img.xz

**Install Dependencies**
`apt update`
`apt full-upgrade`
`apt install clang clang-tools curl gcc gdb git lcov libarchive-dev make sloccount strace swig libtalloc-dev uthash-dev`

**clone the proot repository**
`apt install git`
`git clone https://github.com/proot-me/proot.git`
`cd proot`

**compile the loader**
`LDFLAGS="${LDFLAGS} -static -L/usr/lib/python2.7/config/" make -C src loader.elf build.h`

**compile static proot**
`LDFLAGS="${LDFLAGS} -static -L/usr/lib/python2.7/config/" make -C src proot`

**verify the binaries are static**
`file src/loader.elf`
src/loader.elf: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
`file src/proot`
src/proot: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=fa966edc37f74307ad4440d0d7b3193bdcce5b9d, for GNU/Linux 3.7.0, with debug_info, not stripped

**Comment by oxr463** [comment]
See: https://hub.docker.com/r/muslcc/x86_64

**Comment by oxr463** [comment]
See also: https://github.com/proot-me/proot/issues/313
