### ISSUE TITLE
build error due to inclusion of non-standard header sys/queue.h

### ISSUE THREAD

**Issue by rofl0r** [proot-me/proot#240]
on musl libc, there is no sys/queue.h, as it's not a standard header.
it's more of a standalone library, and license incompatible at that, so musl can't just pick the BSD one and ship it.

```
In file included from ./execve/execve.h:28:0,
                 from ./execve/enter.c:35:
./tracee/tracee.h:29:37: fatal error: sys/queue.h: No such file or directory
 #include <sys/queue.h> /* LIST_*, */
                                     ^
compilation terminated.
In file included from ./cli/note.h:26:0,
                 from ./path/temp.c:11:
./tracee/tracee.h:29:37: fatal error: sys/queue.h: No such file or directory
 #include <sys/queue.h> /* LIST_*, */
                                     ^
```

the header should be copied into the source tree and referenced from there, e.g. `#include "somedir/queue.h"` rather than via `<sys/queue.h>` and it should not be assumed to be available everywhere.

it happens to work only on void linux because they install a "musl-legacy-compat" package by default that ships the header, in order to go the path of least resistance. it doesn't work on any other musl based distro.

## Specifications

  - Proot/Care version: 5.2.0-alpha
  - Host distribution: sabotage linux

**Comment by rofl0r** [comment]
it's even worse than that. after installing queue.h from FreeBSD:

```
In file included from ./path/glue.c:33:0:
./path/binding.h:40:3: error: expected specifier-qualifier-list before 'CIRCLEQ_ENTRY'
   CIRCLEQ_ENTRY(binding) pending;
   ^~~~~~~~~~~~~
./path/binding.h:46:9: error: function definition declared 'typedef'
 typedef CIRCLEQ_HEAD(bindings, binding) Bindings;
         ^~~~~~~~~~~~
./path/binding.h:46:9: warning: return type defaults to 'int' [-Wimplicit-int]
./path/binding.h: In function 'CIRCLEQ_HEAD':
./path/binding.h:46:41: error: expected declaration specifiers before 'Bindings'
 typedef CIRCLEQ_HEAD(bindings, binding) Bindings;
```

it seems the CIRCLE stuff is only defined in the netbsd version.

**Comment by oxr463** [comment]
> it's even worse than that. after installing queue.h from FreeBSD:
> 
> ```
> In file included from ./path/glue.c:33:0:
> ./path/binding.h:40:3: error: expected specifier-qualifier-list before 'CIRCLEQ_ENTRY'
>    CIRCLEQ_ENTRY(binding) pending;
>    ^~~~~~~~~~~~~
> ./path/binding.h:46:9: error: function definition declared 'typedef'
>  typedef CIRCLEQ_HEAD(bindings, binding) Bindings;
>          ^~~~~~~~~~~~
> ./path/binding.h:46:9: warning: return type defaults to 'int' [-Wimplicit-int]
> ./path/binding.h: In function 'CIRCLEQ_HEAD':
> ./path/binding.h:46:41: error: expected declaration specifiers before 'Bindings'
>  typedef CIRCLEQ_HEAD(bindings, binding) Bindings;
> ```
> 
> it seems the CIRCLE stuff is only defined in the netbsd version.

PRoot will never run on FreeBSD. It explicitly mentions in the README.md file that it is Linux-only at this point.

If you're trying to build on musl, try taking a look at the APKBUILD for Alpine Linux (https://git.alpinelinux.org/aports/tree/testing/proot/APKBUILD).

I also wrote this blog post on dependencies (https://proot-me.github.io/blog/dependencies).

Does that help?

**Comment by rofl0r** [comment]
i already got it to build (here is recipe: https://github.com/sabotage-linux/sabotage/commit/cda508d7cc181244d6e27ef90672102ff0c34963 ), thanks. what i'm mentioning is that it would be trivial to add the specific version of the BSD header sys/queue.h that's needed to the source tree of proot itself, rather than relying on that the target linux distribution provides exact that version.

**Comment by oxr463** [comment]
> i already got it to build (here is recipe: [sabotage-linux/sabotage@cda508d](https://github.com/sabotage-linux/sabotage/commit/cda508d7cc181244d6e27ef90672102ff0c34963) ), thanks. what i'm mentioning is that it would be trivial to add the specific version of the BSD header sys/queue.h that's needed to the source tree of proot itself, rather than relying on that the target linux distribution provides exactly that version.

Most Linux distributions already provide this. It would be trivial for you to create a separate package for this header, similar to how Alpine does it (See: https://pkgs.alpinelinux.org/package/edge/main/x86_64/bsd-compat-headers).
