### ISSUE TITLE
README mentions dependency on uthash, but there is none

### ISSUE THREAD

**Issue by rofl0r** [proot-me/proot#241]
## Expected Behavior

Readme accurately describes dependencies.

## Actual Behavior

It doesn't. Actually i wasted about 15 mins clicking around and reading commit histories of both proot and uchash to find out which version of uthash would be necessary, as they're in the process of refactoring their API since 2.5 years.

## Steps to Reproduce the Problem

browse to proot repo, read README.

**Comment by oxr463** [comment]
Here are the dependencies required to build on various distributions (https://proot-me.github.io/blog/dependencies). If you would like to amend the README.md file, feel free to submit a PR. Or, let me know here in this issue what you think should be improved and I can update it.

**Comment by rofl0r** [comment]
well uthash is listed there as a dependency, but i didn't have uthash installed and it built without it just fine. the page looks generally bogus as it lists e.g. clang as a dependency, and then gcc too. really any compiler should do, and coreutils etc are needed for everything really, so there's no need to mention them.

**Comment by oxr463** [comment]
> well uthash is listed there as a dependency, but i didn't have uthash installed and it built without it just fine. the page looks generally bogus as it lists e.g. clang as a dependency, and then gcc too. really any compiler should do, and coreutils etc are needed for everything really, so there's no need to mention them.

Were you building on one of the distributions listed? If so, then I would be surprised to see it build without that package.
Users have asked for explicit dependencies in the past (yes, the compilers), therefore, they have been added to the list.

**Comment by rofl0r** [comment]
i'm 100% certain i don't had uthash installed because i'm the author of my own distro and uthash isn't packaged so far. the build of proot succeeded without any uthash.

there are only 3 possibilities:
- either the uthash dependency was removed at some point,
- its sources have been added to proot,
- or they're only required for the python extension stuff which i didn't build.

you're not the original author of proot, right ?

**Comment by oxr463** [comment]
> i'm 100% certain i don't had uthash installed because i'm the author of my own distro and uthash isn't packaged so far. the build of proot succeeded without any uthash.
> 
> there are only 3 possibilities:
> 
>     * either the uthash dependency was removed at some point,
> 
>     * its sources have been added to proot,
> 
>     * or they're only required for the python extension stuff which i didn't build.
> 
> 
> you're not the original author of proot, right ?

A quick search in the code reveals the following:

```
src/extension/care/care.c:#include <uthash.h>       /* ut*, UT*, HASH*, */
```

CARE is basically it's own program in a way. It was written by the original author. That line was added in 9f5eeb72.

You are free to package whatever you'd like, but that still doesn't mean uthash isn't a dependency.

I am closing this issue since I don't feel like this conversation is contributing anything benefitial to the project. Feel free to reply back or submit a PR if you have anything constructive to add.

**Comment by rofl0r** [comment]
ah, interesting. turned out i had a bug in my recipe so only the first make target passed to the function mk_target was actually passed to make. so i guess i was lucky since i only wanted proot anyway and i certainly didn't want to install the unspecified version of uthash, as, as i mentioned, uthash is a moving target. they're changing their API since 2.5 years and the homepage links to a tarball created from git master rather than a proper release. besides, according to the benchmark released by the author of khash, uthash is dead slow.

so maybe the documentation should be amended to state that uthash is only required for `care`.
and even better, specify the exact version. even better than that, integrate the exact uthash version that is needed inside the source tree since uthash is one of the libs that's quite unlikely to be shipped by a distro as its author encouraged users to drop the sources inside their program file tree.
