### ISSUE TITLE
Please add a link to release of proot from gitlab-pages

### ISSUE THREAD

**Issue by Kamilcuk** [proot-me/proot#244]
The current site on https://proot-me.github.io/#downloads mentions https://github.com/proot-me/proot-static-build/releases that is old and also gitlab-ci/cd stuff is mentioned.
Please consider adding to the site somewhere here https://github.com/proot-me/proot-me.github.io/blob/master/index.html#L171 just a direct link to `https://proot.gitlab.io/proot/bin/proot` - users can just `curl -L 'https://proot.gitlab.io/proot/bin/proot'` to get the latest `proot` from gitlab public pages.

**Comment by oxr463** [comment]
```
curl -LO https://proot.gitlab.io/proot/bin/proot
```

**Comment by oxr463** [comment]
See also: https://github.com/proot-me/proot/issues/239
