### ISSUE TITLE
Add link to repo from docs site

### ISSUE THREAD

**Issue by MichaelCurrin** [proot-me/proot#245]
I was on 

https://proot-me.github.io/

And though it would be nice to have a GitHub link. Like as a GitHub icon in the menu button. Or as badge on its own row.

**Comment by MichaelCurrin** [comment]
Example of icon 

<img width="910" alt="Screen Shot 2021-02-18 at 6 40 52 pm" src="https://user-images.githubusercontent.com/18750745/108390000-e31c5b00-7218-11eb-9b1a-b0e2905ed48e.png">

**Comment by MichaelCurrin** [comment]
Or banner.

<img width="1145" alt="Screen Shot 2021-02-18 at 6 41 57 pm" src="https://user-images.githubusercontent.com/18750745/108390129-047d4700-7219-11eb-88b4-5086f0893100.png">

**Comment by MichaelCurrin** [comment]
Here are 3 markdown badges which you can use. They use shields.io 

```md
[![proot-me - proot](https://img.shields.io/static/v1?label=proot-me&message=proot&color=blue&logo=github)](https://github.com/proot-me/proot)
[![stars - proot](https://img.shields.io/github/stars/proot-me/proot?style=social)](https://github.com/proot-me/proot)
[![forks - proot](https://img.shields.io/github/forks/proot-me/proot?style=social)](https://github.com/proot-me/proot)
```

[![proot-me - proot](https://img.shields.io/static/v1?label=proot-me&message=proot&color=blue&logo=github)](https://github.com/proot-me/proot)
[![stars - proot](https://img.shields.io/github/stars/proot-me/proot?style=social)](https://github.com/proot-me/proot)
[![forks - proot](https://img.shields.io/github/forks/proot-me/proot?style=social)](https://github.com/proot-me/proot)

Generated with [Badge Generator](https://michaelcurrin.github.io/badge-generator/#/repo)

**Comment by oxr463** [comment]
Would this be in the downloads section?

https://proot-me.github.io/#downloads

**Comment by MichaelCurrin** [comment]
The one page site is intimidating to scroll through so I'm worried it won't get found there.

A GitHub link in the menu bar at the very top of the site like here will be effective.

https://babeljs.io/

I found this tool because of a StackOverflow asking for contributors, so if you want to gain contributors it should be quick to get to the code to see what the repo is made of an its popularity. Even having a star count with GitHub icon without the name of the repo is an effective badge
