### ISSUE TITLE
error "bind: Address already in use" when running test-ssssssss

### ISSUE THREAD

**Issue by Apteryks** [proot-me/proot#260]
## Expected Behavior

The test should pass.

## Actual Behavior

The test fails with an "bind: Address already in use" error.  See the output below.

## Steps to Reproduce the Problem

  1. Run the test suite with: `make check -C test V=1 -j 4`.

## Specifications

  - Proot/Care version: v5.2.0-alpha tag
  - Kernel version: 5.12.9-gnu x86_64
  - Host distribution: Guix System
  - Guest distribution: N/A

Using the following build inputs:
```
coreutils-minimal@8.30
libarchive@3.4.2
make@4.2.1
pkg-config@0.29.2
talloc@2.3.2
util-linux@2.35.1
which@2.21
```

## Command Output

```terminal
if [ -e /tmp/guix-build-proot-5.2.0-alpha.drv-0/source/test//rootfs/bin/test-xxxxxxxx ]; then /tmp/guix-build-proot-5.2.0-alpha.drv-0/source/test//../src/proot -b /proc -r /tmp/guix-build-proot-5.2.0-alpha.drv-0/source/test//rootfs /bin/test-xxxxxxxx ; case "$?" in 0)   echo "  CHECK	test-xxxxxxxx ok";; 125) echo "  CHECK	test-xxxxxxxx skipped";; *)   echo "  CHECK	test-xxxxxxxx FAILED"; touch failure ;; esac else echo "  CHECK	test-xxxxxxxx skipped"; fi
++ cd rl1/rl2/..
+ cd_result=1
+ cat rl1/rl2/..
+ cat_result=1
+ readlink rl1/rl2/..
+ readlink_result=1
+ echo 'rl1/rl2/.., 1, 1, 1'
+ for c in ${x4} ""
+ x=rl1/rl2
bind: Address already in use
  CHECK	test-ssssssss FAILED
```

**Comment by Apteryks** [comment]
It is perhaps caused by the fact that the networking support inside the build chroot of GNU Guix is not complete enough.  If you cannot reproduce this in a containerized environment, feel free to close it.

**Comment by oxr463** [comment]
Commit: https://github.com/proot-me/proot/commit/b916c3beb0f8114b87a646be696ec67b12ce8450

**Comment by oxr463** [comment]
@Apteryks are you the new PRoot maintainer for Guix? It would be great to chat sometime on Gitter!

**Comment by Apteryks** [comment]
@oxr463 Hello!  Packages in GNU Guix typically do not have assigned maintainers to them; at least not in an official way; I just happened to notice that building for PRoot for ARM was broken and looked into it. I'd be happy to chat, on Gitter or on #guix (libera.chat), if I can be of help :-). My user name there is 'apteryx'.

**Comment by oxr463** [comment]
@Apteryks can you please test this again.

**Comment by Apteryks** [comment]
@oxr463 passed on latest commit af689de9860e3cad2033bbecce9a7a4a2f9724ad, thank you!

**Comment by oxr463** [comment]
> @oxr463 passed on latest commit [af689de](https://github.com/proot-me/proot/commit/af689de9860e3cad2033bbecce9a7a4a2f9724ad), thank you!

Don't thank me, thank @yuyichao
