### ISSUE TITLE
wine: could not load ntdll.so: (null)

### ISSUE THREAD

**Issue by mariuszkurek** [proot-me/proot#265]
## Expected Behavior
Wine works using proot.
## Actual Behavior
Wine crashes immediately.
## Steps to Reproduce the Problem
```
# mkdir /glibc
# XBPS_ARCH=x86_64 xbps-install -S -R https://alpha.de.repo.voidlinux.org/current -r /glibc base-voidstrap
# PROOT_NO_SECCOMP=1 proot -S /glibc xbps-install void-repo-multilib void-repo-multilib-nonfree void-repo-nonfree
# PROOT_NO_SECCOMP=1 proot -S /glibc xbps-install -S wine-32bit
$ PROOT_NO_SECCOMP=1 proot -R /glibc wine
```
## Specifications

  - Proot/Care version: 5.1.0
  - Kernel version: 5.12.19
  - Host distribution: Void Linux x86_64 musl
  - Guest distribution: Void Linux x86_64 glibc

## Command Output

```
$ PROOT_NO_SECCOMP=1 proot -R /glibc wine
wine: could not load ntdll.so: (null)
```

**Comment by oxr463** [comment]
Thanks for opening this issue.

Can we try cranking up the verbosity on wine?

See: https://wiki.winehq.org/Debug_Channels

**Comment by mariuszkurek** [comment]
```bash
host$ proot -R /glibc
guest$ WINEDEBUG=+all wine
wine: could not load ntdll.so: (null)
```

**Comment by oxr463** [comment]
@mariuszkurek can you test again on the latest v5.3.0 release?

**Comment by oxr463** [comment]
I tested wine inside of an Alpine Linux rootfs and I didn't get that error. I don't know much about Void, but maybe we could try Ubuntu or another distro?

**Comment by mariuszkurek** [comment]
> @mariuszkurek can you test again on the latest v5.3.0 release?

Neither 5.2.0 from Void repo or 5.3.0 static from GitHub changed anything.

> I tested wine inside of an Alpine Linux rootfs and I didn't get that error. I don't know much about Void, but maybe we could try Ubuntu or another distro?

The entire point of me running Wine this way is having a base system using muslc (which doesn't support 32-bit apps, but it's less resource-hungry) and glibc installation only for Wine, while both of them behave exactly the same (package management, configuring and all that jazz). Void is the only distro I know that ship with both, so Alpine, Ubuntu or any other distro that doesn't meet this requirement is not a solution for me.

**Comment by oxr463** [comment]
> Void is the only distro I know that ship with both, so Alpine, Ubuntu or any other distro that doesn't meet this requirement is not a solution for me.

I would recommend filing a bug with Void then. If this issue is not reproducible on any other distribution then it doesn't seem like a PRoot issue to me.
