### ISSUE TITLE
android intercept svc(systemcall)  of ptrace

### ISSUE THREAD

**Issue by w296488320** [proot-me/proot#306]
hi, great developer
Do you know how to intercept svc instructions on android? 
Many of app now will read apk into memory via svc(syscall) open function，Invalid inlinehook was caused。
I know interception can be intercepted via ptrace。But I don't know what to do。Do you have good suggestions or methods?
Thank you desperately for your support！

**Comment by oxr463** [comment]
Hi @w296488320 you might want to ask around in the Termux community, (See: https://wiki.termux.com/wiki/Community) or file an issue on their fork, https://github.com/termux/proot/issues
