### ISSUE TITLE
signal 11 received on arm processor

### ISSUE THREAD

**Issue by cristianrz** [proot-me/proot#312]
Running proot on Debian inside a VM on M1 throws signal 11. Both Debian and proot are the aarch64 builds. Tried different guest distros and they all fail.

## Specifications

  - Proot/Care version: 5.1.0
  - Kernel version: 5.10.0-10 arm64
  - Host distribution: debian
  - Guest distribution: ubuntu

## Command Output

```terminal
$ uname -m
aarch64
$ file /usr/local/bin/proot
/usr/local/bin/proot: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=89e8af53f8c43a4f970f3e420242298cbefeaeca, stripped
$ file rootfs/bin/date
rootfs/bin/date: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=b2cf3190616a362a7c11b384adbd81665a77d989, for GNU/Linux 3.7.0, stripped
$ ./rootfs/bin/date
Mon 20 Dec 14:40:00 CET 2021
$ proot -r rootfs -w / date
proot warning: signal 11 received from process 987781486
```

**Comment by oxr463** [comment]
@cristianrz can you try again using the latest v5.3.0 release:

- https://github.com/proot-me/proot/releases/download/v5.3.0/proot-v5.3.0-aarch64-static

**Comment by cristianrz** [comment]
Works for me now. Thanks.
