### ISSUE TITLE
Proot v5.2 static binary for ARM

### ISSUE THREAD

**Issue by fsquillace** [proot-me/proot#313]
## Expected Behavior

Similarly to v5.1 it would be great to get static binary for proot v5.2 for ARM arch too.
In the latest stable release I can only see the x86_64 static binary only:
https://github.com/proot-me/proot/releases/tag/v5.2.0

## Specifications

  - Proot version: proot 5.2

**Comment by oxr463** [comment]
I've manually built and added static binaries for AARCH64 and ARM for the v5.3.0 release. I'm going to add them for v5.2.0 as well.
