### ISSUE TITLE
Perhaps mention on site/docs that PRoot requires a Linux-kernel host? 

### ISSUE THREAD

**Issue by geoff-codes** [proot-me/PRoot#32]
Hi there —

If I could gently make a suggestion for the PRoot website and/or docs, making an explicit mention of the fact that PRoot requires a Linux _host_?

While I know this might seem obvious, to the user of another POSIX based system, it actually isn't quite. While there are plenty of mentions of Linux _guest_ filesystems, `chroot`, `mount`, and the ptrace system call itself are all common to all Unix-based systems, and neither talloc nor qemu are not Linux-specific either. This (well, for me, at least) is particularly confusing in light of what PRoot **can** do in terms of transparent use of incompatible architectures and binary formats. Myself, (probably being being far too hopeful, I suppose, as I'm in rather desperate need of a userland `chroot` on Darwin and [fakechroot](http://github.com/fakechroot/fakechroot) is also inextricable from glibc, so it seems), read the site and the manual through thoroughly and I believe there is, in fact, no mention that Linux is required host-side. But then, `fatal error: 'linux/limits.h' file not found`...

So I think it possibly might save some others like me a little bit of time (and a few dashed hopes),  if you wouldn't mind noting this requirement somewhere?

:)
~G

**Comment by jopasserat** [comment]
Hopefully the website's first paragraph addresses that.
https://proot-me.github.io/

Please suggest changes in a PR to this repo if not https://github.com/proot-me/proot-me.github.io
