### ISSUE TITLE
Compile from master fails with missing `linux/ashmem.h`

### ISSUE THREAD

**Issue by ruanformigoni** [proot-me/proot#346]
## Expected Behavior

Compile the program and generate the binary.

## Actual Behavior

```bash
./extension/ashmem_memfd/ashmem_memfd.c:5:10: fatal error: linux/ashmem.h: No such file or directory
    5 | #include <linux/ashmem.h> /* ASHMEM_GET_SIZE,  */
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [GNUmakefile:193: extension/ashmem_memfd/ashmem_memfd.o] Error 1
make: Leaving directory '/home/ruan/Repositories/proot/src'
```

## Steps to Reproduce the Problem

  1. Clone from master
  2. Install dependencies
  3. Compile with README.md instructions

**Comment by oxr463** [comment]
Interesting. What distribution version? Kernel version?

**Comment by ruanformigoni** [comment]
The distribution is arch, with kernel `6.1.10-arch1-1`. I also tried it in ubuntu focal and got the same result.

**Comment by ruanformigoni** [comment]
Just figured it out that the issue was introduced by the latest commit, `git reset --hard HEAD^` before compiling fixes it.

**Comment by ruanformigoni** [comment]
My mistake this was not the solution, I don't know what happened but after a re-clone it now always works.

**Comment by oxr463** [comment]
Great! Glad you were able to resolve the issue.
