### ISSUE TITLE
Unable to enter the root user after running termux-chroot command

### ISSUE THREAD

**Issue by laisc7301** [proot-me/proot#358]
运行termux-chroot后无法进入root用户

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Proot/Care version: 5.1.0
  - Kernel version: 4.14.133+
  - Android version: 10
  - Device model: KOZ-AL00
  - Host distribution:
  - Guest distribution:

## Command Output

```terminal
Report issues at https://termux.dev/issues

~ $ whoami
u0_a207
~ $ termux-chroot
~ $ whoami
u0_a207
~ $ 

```

-OR-

[Attached log]()

**Comment by oxr463** [comment]
Please report any issues with Termux here: https://github.com/termux/proot
