### ISSUE TITLE
Clean debian

### ISSUE THREAD

**Issue by guilhem** [proot-me/PRoot#50]
Hi,

I create a [repository](https://github.com/guilhem/proot-debian) with all stuff needed to build debian package in a good way.
It only need #49 to work.

I can give you ownership if you want to. :)

I will also create launchpad project to autobuild packages on a ppa repository.
Can be far easier for any ubuntu user.

**Comment by oxr463** [comment]
> It only need #49 to work.

Closing since issue mentioned has been resolved.
