### ISSUE TITLE
Does PRoot work in a cpanel jailshell?

### ISSUE THREAD

**Issue by cyberic99** [proot-me/proot#79]
Hello

I tried a static proot in a cpanel jailshell. I do not know exactly what restrictions there are...
Everything is done on an x86_64 system.

/bin/cat /dev/null <== works

./proot-x86_64 -v 3 /bin/cat /dev/null :

proot info: binding = /
proot info: pid 72: translate("/" + "/bin/cat")
proot info: pid 72:          -> "/bin/cat"
proot info: pid 72: translate("/" + "/bin/cat")
proot info: pid 72:          -> "/bin/cat"
proot info: exe = /bin/cat
proot info: argv = /bin/cat /dev/null
proot info: initial cwd = /home5/xxx/tmp/tmp
proot info: verbose level = 3
proot info: pid 72: access to "/dev/pts/3" (fd 0) won't be translated until closed
proot info: pid 72: access to "/home5/xxx/tmp/tmp/log" (fd 1) won't be translated until closed
proot info: pid 72: access to "/home5/xxx/tmp/tmp/log" (fd 2) won't be translated until closed
proot info: pid 72: access to "/proc/72/fd" (fd 3) won't be translated until closed
proot info: pid 73: sysenter start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0x6) = 0xffffffffffffffda [0x7fff75084078, 0]
proot info: pid 73: sysenter start: execve(0xb13210, 0x7fff75084300, 0x7fff75084318, 0x8f3370, 0xb13210, 0x0) = 0xffffffffffffffda [0x7fff750840c8, 0]
proot info: pid 73: translate("/" + "/bin/cat")
proot info: pid 73:          -> "/bin/cat"
proot info: pid 73: translate("/" + "/lib64/ld-linux-x86-64.so.2")
proot info: pid 73:          -> "/lib64/ld-2.12.so"
proot info: loader: /tmp/prooted-72-4PzRP2
proot info: pid 73: sysenter start: write(0x2, 0x7fff750819e0, 0xd, 0x0, 0xb0e880, 0x5) = 0xffffffffffffffda [0x7fff75081838, 0]
proot error: proot info: pid 73: sysenter start: write(0x2, 0x7fff75081ac0, 0x12, 0x0, 0xb0e880, 0x8) = 0xffffffffffffffda [0x7fff75081918, 0]
execve("/bin/cat")proot info: pid 73: sysenter start: write(0x2, 0x4b4388, 0x2, 0x0, 0x8f54a0, 0x4b4388) = 0xffffffffffffffda [0x7fff75083fe8, 0]
: proot info: pid 73: sysenter start: write(0x2, 0x7fff750815a0, 0x12, 0x0, 0xb0e880, 0x11) = 0xffffffffffffffda [0x7fff750813f8, 0]
Permission denied
proot info: pid 73: sysenter start: write(0x2, 0x7fff750819e0, 0xc, 0x0, 0xb0e880, 0x5) = 0xffffffffffffffda [0x7fff75081838, 0]
proot info: proot info: pid 73: sysenter start: write(0x2, 0x7fff75081ac0, 0x14b, 0x6f6420726f20646e, 0xb0e880, 0x756f6620746f6e20) = 0xffffffffffffffda [0x7fff75081918, 0]
possible causes:
- the program is a script but its interpreter (eg. /bin/sh) was not found;
- the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
- the program is a foreign binary but qemu was not specified;
- qemu does not work correctly (if specified);
- the loader was not found or doesn't work.proot info: pid 73: sysenter start: write(0x2, 0x8f2c43, 0x1, 0x6f6420726f20646e, 0xa, 0xb0e880) = 0xffffffffffffffda [0x7fff75084008, 0]

proot info: pid 73: sysenter start: write(0x2, 0x7fff75081ad0, 0x28, 0x0, 0xb0e880, 0xc) = 0xffffffffffffffda [0x7fff75081928, 0]
fatal error: see `proot-x86_64 --help`.
proot info: pid 73: sysenter start: exit_group(0x1, 0x0, 0x1, 0xffffffffffffffd0, 0x3c, 0xe7) = 0xffffffffffffffda [0x7fff75084148, 0]
proot info: pid 73: exited with status 1

Thanks

**Comment by cedric-vincent** [comment]
Hello @cyberic99,

> Is there anything more I can do/test? Thx

I really want to solve this issue correctly, so please don't mind
about the delay... Sorry.

Here follows a summary of your experiences with PRoot in a cPanel
Jailshell so far:

- proot v4 works

- proot v5 doesn't work:

  - by default, you get "Permission denied" likely because "/tmp" is
    mounted with "noexec" option.

  - when using an alternate location for the loader you get "Exec
    format error".

Regarding this last point, I think something went wrong during the
download of the loader, for instance "wget" can't download files from
Google Drive.  I moved this file elsewhere, so could you please try
the following commands in your cPanel Jailshell:

    wget static.proot.me/proot-x86_64
    wget static.proot.me/proot-x86_64-v5.1.0-loader
    chmod +x proot-x86_64
    chmod +x proot-x86_64-v5.1.0-loader 
    PROOT_LOADER=./proot-x86_64-v5.1.0-loader ./proot-x86_64 echo OK

Thanks in advance,
Cédric.

**Comment by cyberic99** [comment]
Hello Cédric,

No worries about the delay, it is very nice to you to help me for my particular use case.

So I tried the commands.

I had to add '--no-check-certificate' to wget, in order to get the files.

After that, I have now:

# PROOT_LOADER=./proot-x86_64-v5.1.0-loader ./proot-x86_64 echo OK
OK

And yes, tmpfs is mounted like this:
tmpfs /tmp tmpfs rw,nosuid,noexec,relatime,size=1536000k 0 0

Thank you

**Comment by cedric-vincent** [comment]
On Tue, Jan 06, 2015 at 02:21:03AM -0800, cyberic99 wrote:
> After that, I have now:
> 
> # PROOT_LOADER=./proot-x86_64-v5.1.0-loader ./proot-x86_64 echo OK
> OK
> 
> And yes, tmpfs is mounted like this:
> tmpfs /tmp tmpfs rw,nosuid,noexec,relatime,size=1536000k 0 0

Good news! That means you encountered only one issue: "/tmp" mounted with
"noexec" option. I'll do something soon in this regard, maybe a new
command-line option ("-t") to specify a temporary directory (such an option
is also required to make PRoot works on Android anyway [1])

Thanks for the tests,
Cédric.

[1] https://github.com/corbinlc/gnuroot/issues/33#issuecomment-65198338

**Comment by oxr463** [comment]
Is this issue still occurring after `PROOT_TMP_DIR` was added?

**Comment by cyberic99** [comment]
> Is this issue still occurring after `PROOT_TMP_DIR` was added?

I'd like to test it again, but where can I download an updated static build of PRoot?

**Comment by cyberic99** [comment]
> Is this issue still occurring after `PROOT_TMP_DIR` was added?

I'd like to test it again, but where can I download an updated static build of PRoot?

**Comment by oxr463** [comment]
> I'd like to test it again, but where can I download an updated static build of PRoot?

I'm working on publishing development builds via GitLab CI.

See also: https://github.com/proot-me/proot-static-build/issues/5

**Comment by oxr463** [comment]
@cyberic99, here is a static build from the latest git commit:

<https://gitlab.com/proot/proot/-/jobs/171477139/artifacts/raw/public/bin/proot>

Please let me know if this works for you.

**Comment by cyberic99** [comment]
@oxr463 yet, with the provided binary, it works if I set PROOT_TMP_DIR to another directory.

thanks!

**Comment by oxr463** [comment]
Awesome! Glad to hear it.
