### ISSUE TITLE
Proper Way to Use Link2SymLink in PRoot

### ISSUE THREAD

**Issue by czenzel** [proot-me/PRoot#95]
Hello everyone,

I am very stumped on using Link2Symlink of PRoot and was wondering if somebody has expereinced this issue or could help point me in the right direction. Maybe it is user error.

I have compiled the latest link2symlink for aarch64 for my Android Pixel C tablet running Android 6.0. I have been using Termux for experimentation and copied over the proot and a sample rootfs. Everything runs fine until I try to run apt-get.

I have added the -l option to the proot software; however, on all the packages I try to install, update, or configure using dpkg I receive an error about `status-old` and `function  not implemented`. Before using the link option in proot I was receiving a `permission denined` error.

I am running proot with fakeroot. I was wondering if somebody could point me to a sample program execution line to try (with arguments) to see if I am using proot wrong.

Thanks
Chris Zenzel

**Comment by javierurox** [comment]
Hi, i have the same problem , did you solve this problem finally,?

**Comment by czenzel** [comment]
Hi @javierox 

I haven't had any luck. I tried again last night with a custom compiled proot with link2symlink extension for Termux. It runs; however, I am still receiving the function not implemented error.

I did notice that some links on the extraction of the chroot are also giving errors under Termux.

I am going to see if there is another Terminal Emulator that might work. I have also tried to use BusyBox as the script interpreter, but it still has linking errors. It is kind of making me narrow it to the actual Terminal software with Android 6.x (latest security updates on Pixel C).

Thanks,
Chris Zenzel

**Comment by oxr463** [comment]
Have you tried this with the [termux version of proot](https://github.com/termux/proot)?

**Comment by czenzel** [comment]
Hello @oxr463 - Sorry for the delay. I moved a few times since I issued this ticket and don't have my tablet anymore. Actually in 2016 when i posted this I was being bullied on Twitter. Anyways - if someone else can help you with the ticket that would be great. I do have a Pixel XL 2 that I can try again as well - but low priority on my side as well.
